// Code generated by gx. DO NOT EDIT.

package site

import (
	gx "github.com/alternayte/gx"
)

type LiveTableProps struct {
	// Item is the registry item: "data-table" or "data-table-page".
	Item string
}

func LiveTable(p LiveTableProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/docs/site", "LiveTable", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line LiveTable.gx:9:44
	_b.Add(gx.Text("\n"))
//line LiveTable.gx:10:1
	_b.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "gx-frame gx-frame-block resize-y overflow-hidden rounded-lg border border-border bg-background", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n  "), gx.El("iframe", gx.Attrs{gx.Attr{Key: "class", Value: "block size-full", Kind: gx.AttrText}, gx.Attr{Key: "src", Value: tableDemoStart(p.Item).URL(), Kind: gx.AttrURL, Active: "page"}, gx.Attr{Key: "title", Value: "Data table: live example", Kind: gx.AttrText}, gx.Attr{Key: "loading", Value: "lazy", Kind: gx.AttrText}}), gx.Text("\n"))))
//line LiveTable.gx:12:7
	_b.Add(gx.Text("\n"))
//line LiveTable.gx:13:1
	_b.Add(gx.El("p", gx.Attrs{gx.Attr{Key: "class", Value: "gx-frame-link mt-2 text-right text-xs", Kind: gx.AttrText}, gx.Bool("data-pagefind-ignore", true)}, gx.Frag(gx.Text("\n  "), gx.El("a", gx.Attrs{gx.Attr{Key: "href", Value: tableDemoStart(p.Item).URL(), Kind: gx.AttrURL, Active: "page"}, gx.Attr{Key: "target", Value: "_blank", Kind: gx.AttrText}, gx.Attr{Key: "rel", Value: "noopener", Kind: gx.AttrText}}, gx.Text("Open the preview in a new tab")), gx.Text("\n"))))
//line LiveTable.gx:15:5
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
