// Code generated by gx. DO NOT EDIT.

package site

import (
	gx "github.com/alternayte/gx"
)

type LiveTableProps struct {
	// Item is the registry item: "data-table" or "data-table-page".
	Item string
}

func LiveTable(p LiveTableProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/docs/site", "LiveTable", p); _ok {
			return _n
		}
	}
//line LiveTable.gx:9:44
	return _tLiveTable0.With(
//line LiveTable.gx:11:3
		gx.Open("iframe", gx.Attrs{gx.Attr{Key: "class", Value: "block size-full", Kind: gx.AttrText}, gx.Attr{Key: "src", Value: tableDemoStart(p.Item).URL(), Kind: gx.AttrURL, Active: "page"}, gx.Attr{Key: "title", Value: "Data table: live example", Kind: gx.AttrText}, gx.Attr{Key: "loading", Value: "lazy", Kind: gx.AttrText}}),
//line LiveTable.gx:13:1
		gx.Open("p", gx.Attrs{gx.Attr{Key: "class", Value: "gx-frame-link mt-2 text-right text-xs", Kind: gx.AttrText}, gx.Bool("data-pagefind-ignore", true)}),
//line LiveTable.gx:14:3
		gx.Open("a", gx.Attrs{gx.Attr{Key: "href", Value: tableDemoStart(p.Item).URL(), Kind: gx.AttrURL, Active: "page"}, gx.Attr{Key: "target", Value: "_blank", Kind: gx.AttrText}, gx.Attr{Key: "rel", Value: "noopener", Kind: gx.AttrText}}),
	)
}

var _tLiveTable0 = gx.NewTemplate(
	[]string{"\n<div class=\"gx-frame gx-frame-block resize-y overflow-hidden rounded-lg border border-border bg-background\">\n  <iframe", "></iframe>\n</div>\n<p", ">\n  <a", ">Open the preview in a new tab</a>\n</p>\n"},
	[]int{1, 0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 112, EndStatic: 1, End: 10}, {Slot: 1, Start: 18, EndStatic: 3, End: 39}, {Slot: 2, Start: 4, EndStatic: 3, End: 34}},
	[]gx.TemplateRoot{{El: -1, Slot: -1}, {El: -1, Slot: -1, Name: "div"}, {El: -1, Slot: -1}, {El: 1, Slot: -1}, {El: -1, Slot: -1}},
)
