// Code generated by gx. DO NOT EDIT.

package site

import (
	gx "github.com/alternayte/gx"
	"github.com/alternayte/gx/registry/button"
	"github.com/alternayte/gx/registry/toast"
)

type ToastDemoProps struct {
	Children gx.Node
}

func ToastDemo(p ToastDemoProps) gx.Node {
	var _b gx.Builder
//line ToastDemo.gx:13:80
	_b.Add(gx.Text("\n"))
//line ToastDemo.gx:14:1
	_b.Add(button.Button(button.ButtonProps{Variant: button.Outline, Attrs: gx.Attrs{{Key: "data-docs-toast", Value: ""}}, Children: gx.Text("Show the toast")}))
//line ToastDemo.gx:14:152
	_b.Add(gx.Text("\n"))
//line ToastDemo.gx:15:1
	_b.Add(gx.El("template", gx.Attrs{gx.Bool("data-docs-toast-source", true)}, p.Children))
//line ToastDemo.gx:15:57
	_b.Add(gx.Text("\n"))
//line ToastDemo.gx:16:1
	_b.Add(toast.Toaster(toast.ToasterProps{}))
//line ToastDemo.gx:16:38
	_b.Add(gx.Text("\n"))
//line ToastDemo.gx:17:1
	_b.Add(toastScript())
//line ToastDemo.gx:17:16
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
