// Code generated by gx. DO NOT EDIT.

package starlight

import (
	gx "github.com/alternayte/gx"
)

type HeaderProps struct {
	// Site is the site-wide data: the title, the versions and the social links.
	Site Config
}

func Header(p HeaderProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/starlight-shell", "Header", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line Header.gx:8:1
	_b.Add(gx.El("header", gx.Attrs{gx.Attr{Key: "class", Value: "sl-header", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n  "), gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "sl-header-inner", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n    "), gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "sl-title-wrapper", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n      "), SiteTitle(SiteTitleProps{Site: p.Site}), gx.Text("\n    "))), gx.Text("\n    "), gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "sl-header-search", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n      "), gx.El("button", gx.Attrs{gx.Attr{Key: "class", Value: "sl-search-button", Kind: gx.AttrText}, gx.Attr{Key: "type", Value: "button", Kind: gx.AttrText}, gx.Bool("data-gx-search-open", true), gx.Attr{Key: "aria-label", Value: "Search", Kind: gx.AttrText}, gx.Attr{Key: "aria-keyshortcuts", Value: "Control+K", Kind: gx.AttrText}, gx.Attr{Key: "aria-haspopup", Value: "dialog", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n        "), icon("magnifier", ""), gx.Raw(gx.SafeHTML("\n        <span aria-hidden=\"true\">Search</span>\n        ")), gx.El("kbd", nil, gx.Frag(gx.El("kbd", gx.Attrs{gx.Bool("data-gx-mod-key", true)}, gx.Text("Ctrl")), gx.Raw(gx.SafeHTML("<kbd>K</kbd>")))), gx.Text("\n      "))), gx.Text("\n    "))), gx.Text("\n    "), gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "sl-right-group", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n      "), SocialIcons(SocialIconsProps{Links: p.Site.Links}), gx.Text("\n      "), ThemeSelect(ThemeSelectProps{}), gx.Text("\n    "))), gx.Text("\n  "))), gx.Text("\n"))))
//line Header.gx:25:10
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
