// Code generated by gx. DO NOT EDIT.

package starlight

import (
	gx "github.com/alternayte/gx"
)

type HeaderProps struct {
	// Site is the site-wide data: the title, the versions and the social links.
	Site Config
}

func Header(p HeaderProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/starlight-shell", "Header", p); _ok {
			return _n
		}
	}
//line Header.gx:8:1
	return _tHeader0.With(
//line Header.gx:11:7
		SiteTitle(SiteTitleProps{Site: p.Site}),
//line Header.gx:14:7
		gx.Open("button", gx.Attrs{gx.Attr{Key: "class", Value: "sl-search-button", Kind: gx.AttrText}, gx.Attr{Key: "type", Value: "button", Kind: gx.AttrText}, gx.Bool("data-gx-search-open", true), gx.Attr{Key: "aria-label", Value: "Search", Kind: gx.AttrText}, gx.Attr{Key: "aria-keyshortcuts", Value: "Control+K", Kind: gx.AttrText}, gx.Attr{Key: "aria-haspopup", Value: "dialog", Kind: gx.AttrText}}),
//line Header.gx:15:9
		icon("magnifier", ""),
//line Header.gx:17:14
		gx.Open("kbd", gx.Attrs{gx.Bool("data-gx-mod-key", true)}),
//line Header.gx:21:7
		SocialIcons(SocialIconsProps{Links: p.Site.Links}),
//line Header.gx:22:7
		ThemeSelect(ThemeSelectProps{}),
	)
}

var _tHeader0 = gx.NewTemplate(
	[]string{"<header class=\"sl-header\">\n  <div class=\"sl-header-inner\">\n    <div class=\"sl-title-wrapper\">\n      ", "\n    </div>\n    <div class=\"sl-header-search\">\n      <button", ">\n        ", "\n        <span aria-hidden=\"true\">Search</span>\n        <kbd><kbd", ">Ctrl</kbd><kbd>K</kbd></kbd>\n      </button>\n    </div>\n    <div class=\"sl-right-group\">\n      ", "\n      ", "\n    </div>\n  </div>\n</header>\n"},
	[]int{3, 3, 4, 5, 3, 3},
	[]gx.TemplateEl{{Slot: 1, Start: 53, EndStatic: 4, End: 45}, {Slot: 3, Start: 61, EndStatic: 4, End: 11}},
	[]gx.TemplateRoot{{El: -1, Slot: -1, Name: "header"}, {El: -1, Slot: -1}},
)
