// Code generated by gx. DO NOT EDIT.

package starlight

import (
	gx "github.com/alternayte/gx"
)

type SearchDialogProps struct {
}

func SearchDialog(p SearchDialogProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/starlight-shell", "SearchDialog", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line SearchDialog.gx:3:1
	_b.Add(gx.El("dialog", gx.Attrs{gx.Attr{Key: "class", Value: "sl-search-dialog", Kind: gx.AttrText}, gx.Attr{Key: "id", Value: "gx-search", Kind: gx.AttrText}, gx.Bool("data-gx-search", true), gx.Attr{Key: "data-gx-search-src", Value: "/pagefind/pagefind.js", Kind: gx.AttrText}, gx.Attr{Key: "aria-label", Value: "Search", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n  "), gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "sl-search-frame", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n    "), gx.El("form", gx.Attrs{gx.Attr{Key: "class", Value: "sl-search-form", Kind: gx.AttrText}, gx.Attr{Key: "method", Value: "get", Kind: gx.AttrText}, gx.Attr{Key: "action", Value: "/search", Kind: gx.AttrURL}, gx.Bool("data-gx-search-form", true)}, gx.Frag(gx.Text("\n      "), gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "sl-search-field", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n        "), icon("magnifier", ""), gx.Text("\n        "), gx.El("input", gx.Attrs{gx.Attr{Key: "class", Value: "sl-search-input", Kind: gx.AttrText}, gx.Attr{Key: "type", Value: "search", Kind: gx.AttrText}, gx.Attr{Key: "name", Value: "q", Kind: gx.AttrText}, gx.Attr{Key: "placeholder", Value: "Search", Kind: gx.AttrText}, gx.Bool("data-gx-search-input", true), gx.Attr{Key: "autocomplete", Value: "off", Kind: gx.AttrText}}), gx.Text("\n      "))), gx.Text("\n      "), gx.El("button", gx.Attrs{gx.Attr{Key: "class", Value: "sl-search-close", Kind: gx.AttrText}, gx.Attr{Key: "type", Value: "button", Kind: gx.AttrText}, gx.Bool("data-gx-search-close", true)}, gx.Text("Cancel")), gx.Text("\n    "))), gx.Text("\n    "), gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "sl-search-results", Kind: gx.AttrText}, gx.Bool("data-gx-search-results", true)}), gx.Text("\n  "))), gx.Text("\n"))))
//line SearchDialog.gx:14:10
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
