// Code generated by gx. DO NOT EDIT.

package starlight

import (
	gx "github.com/alternayte/gx"
)

type SiteTitleProps struct {
	// Site is the site-wide data. With two or more Versions, a select shows after the title;
	// with fewer, the Version label shows.
	Site Config
}

func SiteTitle(p SiteTitleProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/starlight-shell", "SiteTitle", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line SiteTitle.gx:9:1
	var _b1 gx.Builder
//line SiteTitle.gx:9:27
	_b1.Add(gx.Text("\n  "))
//line SiteTitle.gx:10:3
	_b1.Add(gx.El("a", gx.Attrs{gx.Attr{Key: "class", Value: "sl-site-title", Kind: gx.AttrText}, gx.Attr{Key: "href", Value: string(gx.URL("/")), Kind: gx.AttrURL, Active: "page"}}, gx.Frag(gx.Text("\n    "), gx.El("span", gx.Attrs{gx.Attr{Key: "translate", Value: "no", Kind: gx.AttrText}}, gx.Text(p.Site.Title)), gx.Text("\n  "))))
//line SiteTitle.gx:12:7
	_b1.Add(gx.Text("\n  "))
//line SiteTitle.gx:13:3
	if len(p.Site.Versions) > 1 {
//line SiteTitle.gx:13:32
		_b1.Add(gx.Text("\n    "))
//line SiteTitle.gx:14:5
		var _b2 gx.Builder
//line SiteTitle.gx:14:106
		_b2.Add(gx.Text("\n      "))
//line SiteTitle.gx:15:7
		for _, v := range p.Site.Versions {
//line SiteTitle.gx:15:42
			_b2.Add(gx.Text("\n        "))
//line SiteTitle.gx:16:9
			_b2.Add(gx.El("option", gx.Attrs{gx.Attr{Key: "value", Value: string(v.Href), Kind: gx.AttrText}, gx.Bool("selected", v.Label == p.Site.Version)}, gx.Text(v.Label)))
//line SiteTitle.gx:16:95
			_b2.Add(gx.Text("\n      "))
		}
//line SiteTitle.gx:17:8
		_b2.Add(gx.Text("\n    "))
		_b1.Add(gx.El("select", gx.Attrs{gx.Attr{Key: "class", Value: "sl-version-select", Kind: gx.AttrText}, gx.Attr{Key: "aria-label", Value: "Documentation version", Kind: gx.AttrText}, gx.Bool("data-gx-goto", true), gx.Attr{Key: "autocomplete", Value: "off", Kind: gx.AttrText}}, _b2.Node()))
//line SiteTitle.gx:18:14
		_b1.Add(gx.Text("\n  "))
	} else {
//line SiteTitle.gx:19:10
		if p.Site.Version != "" {
//line SiteTitle.gx:19:35
			_b1.Add(gx.Text("\n    "))
//line SiteTitle.gx:20:5
			_b1.Add(gx.El("span", gx.Attrs{gx.Attr{Key: "class", Value: "sl-version", Kind: gx.AttrText}, gx.Bool("data-gx-version", true)}, gx.Text(p.Site.Version)))
//line SiteTitle.gx:20:69
			_b1.Add(gx.Text("\n  "))
		}
	}
//line SiteTitle.gx:21:4
	_b1.Add(gx.Text("\n"))
	_b.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "sl-title-row", Kind: gx.AttrText}}, _b1.Node()))
//line SiteTitle.gx:22:7
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
