// Code generated by gx. DO NOT EDIT.

package starlight

import (
	gx "github.com/alternayte/gx"
)

type ThemeSelectProps struct {
}

func ThemeSelect(p ThemeSelectProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/starlight-shell", "ThemeSelect", p); _ok {
			return _n
		}
	}
//line ThemeSelect.gx:3:1
	return _tThemeSelect0.With(
//line ThemeSelect.gx:5:3
		icon("laptop", "sl-select-icon"),
//line ThemeSelect.gx:6:3
		gx.Open("select", gx.Attrs{gx.Attr{Key: "data-gx-theme", Value: "select", Kind: gx.AttrText}, gx.Attr{Key: "autocomplete", Value: "off", Kind: gx.AttrText}}),
//line ThemeSelect.gx:11:3
		icon("down-caret", "sl-select-caret"),
	)
}

var _tThemeSelect0 = gx.NewTemplate(
	[]string{"<label class=\"sl-select\">\n  <span class=\"sr-only\">Select theme</span>\n  ", "\n  <select", ">\n    <option value=\"dark\">Dark</option>\n    <option value=\"light\">Light</option>\n    <option value=\"auto\" selected>Auto</option>\n  </select>\n  ", "\n</label>\n"},
	[]int{1, 1, 1},
	[]gx.TemplateEl{{Slot: 1, Start: 3, EndStatic: 2, End: 141}},
	[]gx.TemplateRoot{{El: -1, Slot: -1, Name: "label"}, {El: -1, Slot: -1}},
)
