// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package dashboard

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/examples/shop/dashboard",
		Name: "dashboard",
		Values: map[string]reflect.Value{
			"BarChart":      reflect.ValueOf(BarChart),
			"Charts":        reflect.ValueOf(Charts),
			"ChartsPanel":   reflect.ValueOf(ChartsPanel),
			"Dashboard":     reflect.ValueOf(Dashboard),
			"DashboardPage": reflect.ValueOf(&DashboardPage).Elem(),
			"Legend":        reflect.ValueOf(Legend),
			"Refresh":       reflect.ValueOf(&Refresh).Elem(),
			"Revenue":       reflect.ValueOf(Revenue),
			"Routes":        reflect.ValueOf(&Routes).Elem(),
			"Sparkline":     reflect.ValueOf(Sparkline),
			"Stepper":       reflect.ValueOf(Stepper),
			"WideTable":     reflect.ValueOf(WideTable),
		},
		Types: map[string]reflect.Type{
			"BarChartProps":    reflect.TypeFor[BarChartProps](),
			"ChartsProps":      reflect.TypeFor[ChartsProps](),
			"DashboardProps":   reflect.TypeFor[DashboardProps](),
			"DashboardSignals": reflect.TypeFor[DashboardSignals](),
			"LegendProps":      reflect.TypeFor[LegendProps](),
			"Point":            reflect.TypeFor[Point](),
			"SparklineProps":   reflect.TypeFor[SparklineProps](),
			"StepperProps":     reflect.TypeFor[StepperProps](),
			"WideTableProps":   reflect.TypeFor[WideTableProps](),
		},
	}
}

var _ constant.Value
