// Package gxstyles writes the generated package that embeds the built
// stylesheet (REQ-STY-02). The app's main calls gx.SetStylesheet with
// gxstyles.CSS().
package gxstyles

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/alternayte/gx/internal/gxconfig"
	"github.com/alternayte/gx/internal/tailwind"
)

// Dir and File name the generated package.
const (
	Dir  = "gxstyles"
	File = "styles_gx.go"
)

// Path returns the generated file path under root.
func Path(root string) string { return filepath.Join(root, Dir, File) }

// ThemePath returns the theme file the app owns.
func ThemePath(root string) string { return filepath.Join(root, "app", "theme.css") }

// Generate returns the Go source that embeds css, for an app with no
// widget.
func Generate(css []byte) []byte { return GenerateAll(css, nil, nil) }

// GenerateAll returns the Go source that embeds the stylesheet of the app,
// the stylesheet of each widget, by the tag of the widget (REQ-ISL-11), and
// the stylesheet of each page route that has its own, by the pattern of the
// route (REQ-STY-13).
func GenerateAll(css []byte, widgets, routes map[string][]byte) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by gx. DO NOT EDIT.\n\n")
	b.WriteString("package gxstyles\n\n")
	b.WriteString("// CSS returns the built stylesheet (REQ-STY-02).\n")
	b.WriteString("func CSS() []byte { return []byte(stylesheet) }\n\n")
	b.WriteString("// Widgets returns the built stylesheet of each widget, by its tag\n")
	b.WriteString("// (REQ-ISL-11). Give it to gx.SetWidgetStylesheets.\n")
	b.WriteString("func Widgets() map[string][]byte {\n")
	tags := make([]string, 0, len(widgets))
	for tag := range widgets {
		tags = append(tags, tag)
	}
	sort.Strings(tags)
	if len(tags) == 0 {
		b.WriteString("\treturn map[string][]byte{}\n")
	} else {
		b.WriteString("\treturn map[string][]byte{\n")
		for _, tag := range tags {
			b.WriteString("\t\t" + strconv.Quote(tag) + ": []byte(" + strconv.Quote(string(widgets[tag])) + "),\n")
		}
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("// Routes returns the built stylesheet of each page route that has its\n")
	b.WriteString("// own, by the pattern of the route (REQ-STY-13). Give it to\n")
	b.WriteString("// gx.SetRouteStylesheets.\n")
	b.WriteString("func Routes() map[string][]byte {\n")
	patterns := make([]string, 0, len(routes))
	for pattern := range routes {
		patterns = append(patterns, pattern)
	}
	sort.Strings(patterns)
	// Two routes with one stylesheet share one constant.
	names := map[string]string{}
	var sheets []string
	if len(patterns) == 0 {
		b.WriteString("\treturn map[string][]byte{}\n")
	} else {
		b.WriteString("\treturn map[string][]byte{\n")
		for _, pattern := range patterns {
			sheet := string(routes[pattern])
			name, ok := names[sheet]
			if !ok {
				name = "routeSheet" + strconv.Itoa(len(sheets))
				names[sheet] = name
				sheets = append(sheets, sheet)
			}
			b.WriteString("\t\t" + strconv.Quote(pattern) + ": []byte(" + name + "),\n")
		}
		b.WriteString("\t}\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("const stylesheet = " + strconv.Quote(string(css)) + "\n")
	for i, sheet := range sheets {
		b.WriteString("\nconst routeSheet" + strconv.Itoa(i) + " = " + strconv.Quote(sheet) + "\n")
	}
	return []byte(b.String())
}

// RouteClassesPath returns the file with the class list of each page route,
// which the compiler writes.
func RouteClassesPath(root string) string {
	return filepath.Join(root, ".gx", "route-classes.json")
}

// BuildRoutes builds the stylesheet of each page route of the app that has
// a class list of its own (REQ-STY-13): Tailwind reads the theme of the app
// and the class list of the route. Two routes with one list share one run.
// limit is the largest number of distinct lists. Above it, BuildRoutes
// builds nothing and returns a notice that says so: each page then links
// the stylesheet of the app.
func BuildRoutes(ctx context.Context, root string, minify bool, limit int) (sheets map[string][]byte, notice string, err error) {
	data, err := os.ReadFile(RouteClassesPath(root))
	if errors.Is(err, os.ErrNotExist) || (err == nil && len(bytes.TrimSpace(data)) == 0) {
		return nil, "", nil
	}
	if err != nil {
		return nil, "", err
	}
	var lists map[string][]string
	if err := json.Unmarshal(data, &lists); err != nil {
		return nil, "", errors.New("gxstyles: " + RouteClassesPath(root) + " is not the class list of the routes; run gx generate")
	}
	return BuildRouteLists(ctx, root, lists, minify, limit)
}

// BuildRouteLists builds the stylesheet of each route from its class list,
// by the pattern of the route.
func BuildRouteLists(ctx context.Context, root string, lists map[string][]string, minify bool, limit int) (map[string][]byte, string, error) {
	if limit < 0 || len(lists) == 0 {
		return nil, "", nil
	}
	// The distinct lists, in the order of the patterns.
	patterns := make([]string, 0, len(lists))
	for pattern := range lists {
		patterns = append(patterns, pattern)
	}
	sort.Strings(patterns)
	sets := map[string][]string{}
	var order []string
	for _, pattern := range patterns {
		key := strings.Join(lists[pattern], "\n")
		if _, ok := sets[key]; !ok {
			order = append(order, key)
		}
		sets[key] = append(sets[key], pattern)
	}
	if len(order) > limit {
		return nil, "gx: the page routes have " + strconv.Itoa(len(order)) + " distinct class sets, and the limit is " + strconv.Itoa(limit) +
			" (route_sheets in the [styles] table of gx.toml); each page links app.css", nil
	}
	themePath := ThemePath(root)
	theme, err := os.ReadFile(themePath)
	if err != nil {
		return nil, "", err
	}
	dir := filepath.Join(root, ".gx", "routes")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, "", err
	}
	tw := &tailwind.Manager{Root: root}
	out := map[string][]byte{}
	for i, key := range order {
		list := filepath.Join(dir, strconv.Itoa(i)+".txt")
		if err := os.WriteFile(list, []byte(key+"\n"), 0o644); err != nil {
			return nil, "", err
		}
		input, err := widgetTheme(theme, filepath.ToSlash(list))
		if err != nil {
			return nil, "", err
		}
		css, err := tw.BuildInput(ctx, input, filepath.Dir(themePath), filepath.Join(dir, strconv.Itoa(i)+".css"))
		if err != nil {
			return nil, "", err
		}
		for _, pattern := range sets[key] {
			out[pattern] = css
		}
	}
	return out, "", nil
}

// WidgetClassesPath returns the file with the class list of each widget,
// which the compiler writes.
func WidgetClassesPath(root string) string {
	return filepath.Join(root, ".gx", "widget-classes.json")
}

// BuildWidgets builds the stylesheet of each widget of the app: Tailwind
// reads the theme of the app and the class list of one widget, and ShadowCSS
// makes the result work in a shadow root (REQ-ISL-11). The build is minified
// in each mode, because ShadowCSS reads that form.
func BuildWidgets(ctx context.Context, root string) (map[string][]byte, error) {
	data, err := os.ReadFile(WidgetClassesPath(root))
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	if len(bytes.TrimSpace(data)) == 0 {
		// The app has no widget.
		return nil, nil
	}
	var lists map[string][]string
	if err := json.Unmarshal(data, &lists); err != nil {
		return nil, errors.New("gxstyles: " + WidgetClassesPath(root) + " is not the class list of the widgets; run gx generate")
	}
	return BuildWidgetLists(ctx, root, lists)
}

// BuildWidgetLists builds the stylesheet of each widget from its class
// list, by the tag of the widget.
func BuildWidgetLists(ctx context.Context, root string, lists map[string][]string) (map[string][]byte, error) {
	if len(lists) == 0 {
		return nil, nil
	}
	themePath := ThemePath(root)
	theme, err := os.ReadFile(themePath)
	if err != nil {
		return nil, err
	}
	dir := filepath.Join(root, ".gx", "widgets")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	tw := &tailwind.Manager{Root: root}
	out := map[string][]byte{}
	for tag, classes := range lists {
		list := filepath.Join(dir, tag+".txt")
		if err := os.WriteFile(list, []byte(strings.Join(classes, "\n")+"\n"), 0o644); err != nil {
			return nil, err
		}
		input, err := widgetTheme(theme, filepath.ToSlash(list))
		if err != nil {
			return nil, err
		}
		// The input comes on the standard input, from the directory of
		// the theme, so each relative path of the theme holds.
		css, err := tw.BuildInput(ctx, input, filepath.Dir(themePath), filepath.Join(dir, tag+".css"))
		if err != nil {
			return nil, err
		}
		if out[tag], err = ShadowCSS(css); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// Build runs Tailwind when the app owns app/theme.css and writes the
// generated stylesheet package (REQ-STY-02). It reports false when the app
// has no theme.
func Build(ctx context.Context, root string, minify bool) (bool, error) {
	if abs, err := filepath.Abs(root); err == nil {
		root = abs
	}
	theme := ThemePath(root)
	if _, err := os.Stat(theme); err != nil {
		return false, nil
	}
	css, err := (&tailwind.Manager{Root: root}).Build(ctx, theme, minify)
	if err != nil {
		return false, err
	}
	widgets, err := BuildWidgets(ctx, root)
	if err != nil {
		return false, err
	}
	// A production build has a stylesheet for each page route. A dev
	// build has the stylesheet of the app only: the dev loop swaps that
	// one file (REQ-STY-13).
	var routes map[string][]byte
	if minify {
		limit := gxconfig.DefaultRouteSheets
		if cfg, err := gxconfig.Load(root); err == nil && cfg.RouteSheets != 0 {
			limit = cfg.RouteSheets
		}
		var notice string
		if routes, notice, err = BuildRoutes(ctx, root, minify, limit); err != nil {
			return false, err
		}
		if notice != "" {
			fmt.Fprintln(os.Stderr, notice)
		}
	}
	path := Path(root)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, GenerateAll(css, widgets, routes), 0o644); err != nil {
		return false, err
	}
	// The tokens of the theme as Go values, for an email (REQ-STY-14).
	themeCSS, err := os.ReadFile(theme)
	if err != nil {
		return false, err
	}
	if err := writeIfChanged(TokensPath(root), GenerateTokens(themeCSS)); err != nil {
		return false, err
	}
	return true, nil
}

// writeIfChanged writes a generated file only when its content changes, so
// the dev loop sees no change of a file that is the same.
func writeIfChanged(path string, data []byte) error {
	if old, err := os.ReadFile(path); err == nil && bytes.Equal(old, data) {
		return nil
	}
	return os.WriteFile(path, data, 0o644)
}
