// Code generated by gx. DO NOT EDIT.

package button

import (
	gx "github.com/alternayte/gx"
)

type ButtonProps struct {
	Variant  Variant
	Size     Size
	Type     string
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func Button(p ButtonProps) gx.Node {
	var _b gx.Builder
//line Button.gx:12:1
	_b.Add(gx.El("button", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: p.class(), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "type", Value: p.typeAttr(), Kind: gx.AttrText}}, p.Attrs), p.Children))
//line Button.gx:12:81
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
