// Code generated by gx. DO NOT EDIT.

package route

import (
	"fmt"
	gx "github.com/alternayte/gx"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// Pattern returns the method and pattern of List.
func (List) Pattern() string { return "GET /datatable" }

// Bind fills List from the request.
func (in *List) Bind(r *http.Request) error {
	if v := r.URL.Query().Get("q"); v != "" {
		in.Q = string(v)
	}
	if v := r.URL.Query().Get("sort"); v != "" {
		in.Sort = string(v)
	}
	if in.Sort == "" {
		in.Sort = "name"
	}
	if v := r.URL.Query().Get("dir"); v != "" {
		in.Dir = string(v)
	}
	if in.Dir == "" {
		in.Dir = "asc"
	}
	if v := r.URL.Query().Get("page"); v != "" {
		x, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("gx: Page: %w", err)
		}
		in.Page = int(x)
	}
	if in.Page == 0 {
		in.Page = 1
	}
	return nil
}

// URL returns the path of List.
func (in List) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("datatable")
	q := url.Values{}
	if in.Q != "" {
		q.Set("q", in.Q)
	}
	if in.Sort != "" && in.Sort != "name" {
		q.Set("sort", in.Sort)
	}
	if in.Dir != "" && in.Dir != "asc" {
		q.Set("dir", in.Dir)
	}
	if in.Page != 0 && in.Page != 1 {
		q.Set("page", strconv.FormatInt(int64(in.Page), 10))
	}
	if s := q.Encode(); s != "" {
		b.WriteString("?")
		b.WriteString(s)
	}
	return gx.BasePath() + b.String()
}
