// Code generated by gx. DO NOT EDIT.

package carousel

import (
	gx "github.com/alternayte/gx"
)

type CarouselProps struct {
	// Id is the id of the root element.
	Id string
	// Label is the accessible name of the carousel.
	Label string
	// Orientation sets the direction of the slides: Horizontal or Vertical.
	Orientation Orientation
	// Class adds classes to the root element.
	Class string
	// Children are the slides: one CarouselItem for each.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func Carousel(p CarouselProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/carousel", "Carousel", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line Carousel.gx:18:1
	_b.Add(gx.El("section", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx(rootClass, p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "id", Value: p.Id, Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "carousel", Kind: gx.AttrText}, gx.Attr{Key: "aria-roledescription", Value: "carousel", Kind: gx.AttrText}, gx.Attr{Key: "aria-label", Value: p.label(), Kind: gx.AttrText}, gx.Attr{Key: "data-orientation", Value: string(p.orientation()), Kind: gx.AttrText}}, p.Attrs), gx.Frag(gx.Text("\n  "), gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: viewportClass[p.orientation()], Kind: gx.AttrText}, gx.Attr{Key: "id", Value: p.viewportID(), Kind: gx.AttrText}, gx.Attr{Key: "tabindex", Value: "0", Kind: gx.AttrText}, gx.Attr{Key: "role", Value: "group", Kind: gx.AttrText}, gx.Attr{Key: "aria-label", Value: p.label() + " slides", Kind: gx.AttrText}}, p.Children), gx.Text("\n  "), CarouselControls(CarouselControlsProps{Viewport: p.viewportID(), Orientation: string(p.orientation()), PreviousLabel: "Previous slide", NextLabel: "Next slide", StatusText: statusText, Classes: controlClasses}, gx.IslandLoad("eager")), gx.Text("\n"))))
//line Carousel.gx:21:11
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
