// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package gxdev_gallery

import (
	gx "github.com/alternayte/gx"
	inputgroup "github.com/alternayte/gx/registry/input-group"
)

// Fixtures returns every component fixture for the dev gallery
// (REQ-AI-03).
func Fixtures() []gx.Fixture {
	return []gx.Fixture{
		{Component: "InputGroup", Name: "Text", Node: func() gx.Node { return inputgroup.InputGroup(inputgroup.InputGroupTextFixtures["Text"]) }},
		{Component: "InputGroupAddon", Missing: true},
		{Component: "InputGroupInput", Missing: true},
		{Component: "InputGroupText", Missing: true},
	}
}
