// Code generated by gx. DO NOT EDIT.

package buttongroup

import (
	gx "github.com/alternayte/gx"
)

type ButtonGroupProps struct {
	Children gx.Node
	Class    string
	Attrs    gx.Attrs
}

func ButtonGroup(p ButtonGroupProps) gx.Node {
	var _b gx.Builder
//line ButtonGroup.gx:9:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("inline-flex -space-x-px shadow-xs [&>button]:rounded-none [&>button:first-child]:rounded-l-md [&>button:last-child]:rounded-r-md [&>button:not(:first-child)]:border-l-0", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "role", Value: "group", Kind: gx.AttrText}}, p.Attrs), p.Children))
//line ButtonGroup.gx:9:245
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
