// Code generated by gx. DO NOT EDIT.

package table

import (
	gx "github.com/alternayte/gx"
)

type TableBodyProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the rows of the body.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func TableBody(p TableBodyProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/table", "TableBody", p); _ok {
			return _n
		}
	}
//line TableBody.gx:12:1
	return _tTableBody0.With(
//line TableBody.gx:12:1
		gx.Open("tbody", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("[&_tr:last-child]:border-0", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "table-body", Kind: gx.AttrText}}, p.Attrs)),
//line TableBody.gx:12:97
		p.Children,
	)
}

var _tTableBody0 = gx.NewTemplate(
	[]string{"<tbody", ">", "</tbody>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 8}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
