// Code generated by gx. DO NOT EDIT.

package item

import (
	gx "github.com/alternayte/gx"
)

type ItemFooterProps struct {
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func ItemFooter(p ItemFooterProps) gx.Node {
	var _b gx.Builder
//line ItemFooter.gx:9:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex basis-full items-center justify-between", p.Class), Kind: gx.AttrText}}, p.Attrs), p.Children))
//line ItemFooter.gx:9:108
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
