// Code generated by gx. DO NOT EDIT.

package item

import (
	gx "github.com/alternayte/gx"
)

type ItemDescriptionProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the description text.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func ItemDescription(p ItemDescriptionProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/item", "ItemDescription", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line ItemDescription.gx:12:1
	_b.Add(gx.El("p", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("line-clamp-2 text-sm leading-normal font-normal text-balance text-muted-foreground [&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "item-description", Kind: gx.AttrText}}, p.Attrs), p.Children))
//line ItemDescription.gx:12:237
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
