// Code generated by gx. DO NOT EDIT.

package email

import (
	gx "github.com/alternayte/gx"
)

type ColumnProps struct {
	// Width is the width of the column in pixels. Zero shares the width of the row.
	Width int
	// Align is the horizontal position of the content: Left, Center or Right.
	Align Align
	// Children is the content of the column.
	Children gx.Node
}

func Column(p ColumnProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/email", "Column", p); _ok {
			return _n
		}
	}
//line Column.gx:12:1
	return _tColumn0.With(
//line Column.gx:12:1
		gx.Open("td", gx.Attrs{gx.Attr{Key: "style", Value: string(gx.StyleJoin(gx.Style(p.style()))), Kind: gx.AttrStyle}, gx.Attr{Key: "align", Value: p.Align.attr(), Kind: gx.AttrText}}),
//line Column.gx:12:46
		p.Children,
	)
}

var _tColumn0 = gx.NewTemplate(
	[]string{"<td", ">", "</td>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 5}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
