// Code generated by gx. DO NOT EDIT.

package email

import (
	gx "github.com/alternayte/gx"
)

type HeadingProps struct {
	// Level is the level of the heading: 1, 2 or 3.
	Level int
	// Align is the horizontal position of the heading: Left, Center or Right.
	Align Align
	// Children is the text of the heading.
	Children gx.Node
}

func Heading(p HeadingProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/email", "Heading", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line Heading.gx:12:1
	switch p.level() {
	case 2:
//line Heading.gx:13:8
		_b.Add(_tHeading0.With(
//line Heading.gx:14:3
			gx.Open("h2", gx.Attrs{gx.Attr{Key: "style", Value: string(gx.StyleJoin(gx.Style(p.style()))), Kind: gx.AttrStyle}}),
//line Heading.gx:14:25
			p.Children,
		))
	case 3:
//line Heading.gx:15:8
		_b.Add(_tHeading1.With(
//line Heading.gx:16:3
			gx.Open("h3", gx.Attrs{gx.Attr{Key: "style", Value: string(gx.StyleJoin(gx.Style(p.style()))), Kind: gx.AttrStyle}}),
//line Heading.gx:16:25
			p.Children,
		))
	default:
//line Heading.gx:17:9
		_b.Add(_tHeading2.With(
//line Heading.gx:18:3
			gx.Open("h1", gx.Attrs{gx.Attr{Key: "style", Value: string(gx.StyleJoin(gx.Style(p.style()))), Kind: gx.AttrStyle}}),
//line Heading.gx:18:25
			p.Children,
		))
	}
//line Heading.gx:19:2
	_b.Add(_tHeading3)
	return _b.Node()
}

var _tHeading0 = gx.NewTemplate(
	[]string{"\n  <h2", ">", "</h2>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 3, EndStatic: 2, End: 5}},
	[]gx.TemplateRoot{{El: -1, Slot: -1}, {El: 0, Slot: -1}, {El: -1, Slot: -1}},
)

var _tHeading1 = gx.NewTemplate(
	[]string{"\n  <h3", ">", "</h3>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 3, EndStatic: 2, End: 5}},
	[]gx.TemplateRoot{{El: -1, Slot: -1}, {El: 0, Slot: -1}, {El: -1, Slot: -1}},
)

var _tHeading2 = gx.NewTemplate(
	[]string{"\n  <h1", ">", "</h1>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 3, EndStatic: 2, End: 5}},
	[]gx.TemplateRoot{{El: -1, Slot: -1}, {El: 0, Slot: -1}, {El: -1, Slot: -1}},
)

var _tHeading3 = gx.NewTemplate(
	[]string{"\n"},
	[]int{},
	nil,
	[]gx.TemplateRoot{{El: -1, Slot: -1}},
).With()
