// Code generated by gx. DO NOT EDIT.

package dropdownmenu

import (
	gx "github.com/alternayte/gx"
	"github.com/alternayte/gx/examples/shop/ui/icons"
)

type DropdownMenuSubTriggerProps struct {
	// Inset adds left padding, so the trigger lines up with the checkbox and radio items.
	Inset bool
	// Disabled turns the trigger off. The arrow keys pass it.
	Disabled bool
	// Class adds classes to the root element.
	Class string
	// Children is the label of the trigger. A chevron follows it.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func DropdownMenuSubTrigger(p DropdownMenuSubTriggerProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/dropdown-menu", "DropdownMenuSubTrigger", p); _ok {
			return _n
		}
	}
//line DropdownMenuSubTrigger.gx:18:1
	return _tDropdownMenuSubTrigger0.With(
//line DropdownMenuSubTrigger.gx:18:1
		gx.Open("button", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex w-full cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-left text-sm outline-hidden select-none hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground aria-expanded:bg-accent aria-expanded:text-accent-foreground disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground", insetClass[p.Inset], p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "type", Value: "button", Kind: gx.AttrText}, gx.Attr{Key: "role", Value: "menuitem", Kind: gx.AttrText}, gx.Attr{Key: "tabindex", Value: "-1", Kind: gx.AttrText}, gx.Attr{Key: "aria-haspopup", Value: "menu", Kind: gx.AttrText}, gx.Attr{Key: "aria-expanded", Value: "false", Kind: gx.AttrText}, gx.Bool("disabled", p.Disabled)}, rovingItem(p.Disabled), p.Attrs)),
//line DropdownMenuSubTrigger.gx:19:3
		p.Children,
//line DropdownMenuSubTrigger.gx:20:3
		icons.ChevronRight(icons.ChevronRightProps{Label: "", Class: "ml-auto size-4"}),
	)
}

var _tDropdownMenuSubTrigger0 = gx.NewTemplate(
	[]string{"<button", ">\n  ", "\n  ", "\n</button>\n"},
	[]int{0, 1, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 3, End: 10}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
