// Code generated by gx. DO NOT EDIT.

package dropdownmenu

import (
	gx "github.com/alternayte/gx"
	"github.com/alternayte/gx/examples/shop/ui/icons"
)

type DropdownMenuCheckboxItemProps struct {
	// Name is the name attribute of the checkbox input. A form or a signal reads it.
	Name string
	// Value is the value that the form sends when the item is checked.
	Value string
	// Checked sets the item as checked on the first render.
	Checked bool
	// Disabled turns the item off. The arrow keys pass it.
	Disabled bool
	// Class adds classes to the root element.
	Class string
	// Children is the label of the item.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func DropdownMenuCheckboxItem(p DropdownMenuCheckboxItemProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/dropdown-menu", "DropdownMenuCheckboxItem", p); _ok {
			return _n
		}
	}
//line DropdownMenuCheckboxItem.gx:22:1
	return _tDropdownMenuCheckboxItem0.With(
//line DropdownMenuCheckboxItem.gx:22:1
		gx.Open("label", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("relative flex cursor-default items-center gap-2 rounded-sm py-1.5 pr-2 pl-8 text-sm select-none hover:bg-accent hover:text-accent-foreground has-[:focus]:bg-accent has-[:focus]:text-accent-foreground has-[:disabled]:pointer-events-none has-[:disabled]:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4", p.Class), Kind: gx.AttrText}}, p.Attrs)),
//line DropdownMenuCheckboxItem.gx:23:3
		gx.Open("input", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: "peer sr-only", Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "type", Value: "checkbox", Kind: gx.AttrText}, gx.Attr{Key: "role", Value: "menuitemcheckbox", Kind: gx.AttrText}, gx.Attr{Key: "tabindex", Value: "-1", Kind: gx.AttrText}, gx.Attr{Key: "name", Value: p.Name, Kind: gx.AttrText}, gx.Attr{Key: "value", Value: p.Value, Kind: gx.AttrText}, gx.Bool("checked", p.Checked), gx.Bool("disabled", p.Disabled)}, rovingItem(p.Disabled))),
//line DropdownMenuCheckboxItem.gx:24:126
		icons.Check(icons.CheckProps{Label: "", Class: "size-4"}),
//line DropdownMenuCheckboxItem.gx:25:3
		p.Children,
	)
}

var _tDropdownMenuCheckboxItem0 = gx.NewTemplate(
	[]string{"<label", ">\n  <input", ">\n  <span class=\"pointer-events-none invisible absolute left-2 flex size-3.5 items-center justify-center peer-checked:visible\">", "</span>\n  ", "\n</label>\n"},
	[]int{0, 1, 2, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 4, End: 9}, {Slot: 1, Start: 4, EndStatic: 2, End: 1}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
