// Code generated by gx. DO NOT EDIT.

package datepicker

import (
	gx "github.com/alternayte/gx"
	button "github.com/alternayte/gx/examples/shop/ui/button"
	"github.com/alternayte/gx/examples/shop/ui/calendar"
	"github.com/alternayte/gx/examples/shop/ui/popover"
)

type DatePickerProps struct {
	// Id is the id of the date input. A label points at it.
	Id string
	// Name is the form field name. The form sends the day as YYYY-MM-DD.
	Name string
	// Value is the chosen day of the first render, as YYYY-MM-DD.
	Value string
	// Min is the first day that a user can choose, as YYYY-MM-DD.
	Min string
	// Max is the last day that a user can choose, as YYYY-MM-DD.
	Max string
	// Placeholder is the text of the trigger with no chosen day.
	Placeholder string
	// Label is the accessible name of the date input.
	Label string
	// WeekStart is the first day of the week: calendar.Sunday or calendar.Monday.
	WeekStart calendar.WeekStart
	// Locale is the language of the month and day names, as a BCP 47 tag. Empty means the language of the page.
	Locale string
	// Class adds classes to the root element.
	Class string
	// Attrs adds HTML attributes to the date input.
	Attrs gx.Attrs
}

func DatePicker(p DatePickerProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/date-picker", "DatePicker", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line DatePicker.gx:31:1
	_b.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("inline-block", p.Class), Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "date-picker", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n  "), popover.PopoverTrigger(popover.PopoverTriggerProps{Id: p.popoverID(), Variant: button.Outline, Size: button.Md, Class: triggerClass, Children: gx.El("span", gx.Attrs{gx.Attr{Key: "class", Value: displayClass, Kind: gx.AttrText}, gx.Attr{Key: "id", Value: p.displayID(), Kind: gx.AttrText}, gx.Attr{Key: "data-empty", Value: p.empty(), Kind: gx.AttrText}}, gx.Text(p.text())), Attrs: nil}), gx.Text("\n  "), popover.Popover(popover.PopoverProps{Id: p.popoverID(), Align: popover.Start, Class: "w-auto p-0", Children: calendar.Calendar(calendar.CalendarProps{Id: p.Id, Name: p.Name, Value: p.Value, Month: "", Min: p.Min, Max: p.Max, Label: p.Label, WeekStart: p.WeekStart, Locale: p.Locale, Display: p.displayID(), Popover: p.popoverID(), Class: "border-0", Attrs: p.Attrs}), Attrs: nil}), gx.Text("\n"))))
//line DatePicker.gx:38:7
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
