// Code generated by gx. DO NOT EDIT.

package email

import (
	gx "github.com/alternayte/gx"
)

type ButtonProps struct {
	// Href is the address that the button opens. gx.RenderEmail makes a site path an absolute URL.
	Href gx.URL
	// Align is the horizontal position of the button: Left, Center or Right.
	Align Align
	// Children is the label of the button.
	Children gx.Node
}

func Button(p ButtonProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/email", "Button", p); _ok {
			return _n
		}
	}
//line Button.gx:12:1
	return _tButton0.With(
//line Button.gx:12:1
		gx.Open("table", gx.Attrs{gx.Attr{Key: "style", Value: string(gx.StyleJoin(gx.Style("margin:0 0 16px"))), Kind: gx.AttrStyle}, gx.Attr{Key: "role", Value: "presentation", Kind: gx.AttrText}, gx.Attr{Key: "align", Value: p.Align.attr(), Kind: gx.AttrText}, gx.Attr{Key: "cellpadding", Value: "0", Kind: gx.AttrText}, gx.Attr{Key: "cellspacing", Value: "0", Kind: gx.AttrText}, gx.Attr{Key: "border", Value: "0", Kind: gx.AttrText}}),
//line Button.gx:15:7
		gx.Open("td", gx.Attrs{gx.Attr{Key: "style", Value: string(gx.StyleJoin(gx.Style("background-color:var(--primary);border-radius:var(--radius)"))), Kind: gx.AttrStyle}, gx.Attr{Key: "align", Value: "center", Kind: gx.AttrText}}),
//line Button.gx:16:9
		gx.Open("a", gx.Attrs{gx.Attr{Key: "style", Value: string(gx.StyleJoin(gx.Style("display:inline-block;padding:12px 20px;font-family:Helvetica,Arial,sans-serif;font-size:16px;line-height:24px;font-weight:700;color:var(--primary-foreground);text-decoration:none"))), Kind: gx.AttrStyle}, gx.Attr{Key: "href", Value: string(p.Href), Kind: gx.AttrURL, Active: "page"}}),
//line Button.gx:16:213
		p.Children,
	)
}

var _tButton0 = gx.NewTemplate(
	[]string{"<table", ">\n  <tbody>\n    <tr>\n      <td", ">\n        <a", ">", "</a>\n      </td>\n    </tr>\n  </tbody>\n</table>\n"},
	[]int{0, 3, 4, 5},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 4, End: 46}, {Slot: 1, Start: 27, EndStatic: 4, End: 16}, {Slot: 2, Start: 10, EndStatic: 4, End: 4}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
