// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package gxdev_gallery

import (
	gx "github.com/alternayte/gx"
	skeleton "github.com/alternayte/gx/registry/skeleton"
)

// Fixtures returns every component fixture for the dev gallery
// (REQ-AI-03).
func Fixtures() []gx.Fixture {
	return []gx.Fixture{
		{Component: "Skeleton", Name: "Card", Node: func() gx.Node { return skeleton.Skeleton(skeleton.SkeletonFixtures["Card"]) }},
		{Component: "Skeleton", Name: "Circle", Node: func() gx.Node { return skeleton.Skeleton(skeleton.SkeletonFixtures["Circle"]) }},
		{Component: "Skeleton", Name: "Line", Node: func() gx.Node { return skeleton.Skeleton(skeleton.SkeletonFixtures["Line"]) }},
	}
}
