// Code generated by gx. DO NOT EDIT.

package checkbox

import (
	gx "github.com/alternayte/gx"
)

type CheckboxProps struct {
	Name     string
	Value    string
	Checked  bool
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func Checkbox(p CheckboxProps) gx.Node {
	var _b gx.Builder
//line Checkbox.gx:12:1
	var _b1 gx.Builder
//line Checkbox.gx:12:79
	_b1.Add(gx.Text("\n  "))
//line Checkbox.gx:13:3
	_b1.Add(gx.El("input", gx.Attrs{gx.Attr{Key: "class", Value: "size-4 rounded border-input accent-primary", Kind: gx.AttrText}, gx.Attr{Key: "type", Value: "checkbox", Kind: gx.AttrText}, gx.Attr{Key: "name", Value: p.Name, Kind: gx.AttrText}, gx.Attr{Key: "value", Value: p.Value, Kind: gx.AttrText}, gx.Bool("checked", p.Checked)}))
//line Checkbox.gx:13:129
	_b1.Add(gx.Text("\n  "))
//line Checkbox.gx:14:3
	if p.Children != nil {
//line Checkbox.gx:14:25
		_b1.Add(gx.Text("\n    "))
//line Checkbox.gx:15:5
		_b1.Add(gx.El("span", nil, p.Children))
//line Checkbox.gx:15:30
		_b1.Add(gx.Text("\n  "))
	}
//line Checkbox.gx:16:4
	_b1.Add(gx.Text("\n"))
	_b.Add(gx.El("label", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex items-center gap-2 text-sm", p.Class), Kind: gx.AttrText}}, p.Attrs), _b1.Node()))
//line Checkbox.gx:17:9
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
