// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package gxdev_gallery

import (
	gx "github.com/alternayte/gx"
	field "github.com/alternayte/gx/registry/field"
)

// Fixtures returns every component fixture for the dev gallery
// (REQ-AI-03).
func Fixtures() []gx.Fixture {
	return []gx.Fixture{
		{Component: "Field", Name: "Legend", Node: func() gx.Node { return field.Field(field.FieldLegendFixtures["Legend"]) }},
		{Component: "FieldDescription", Missing: true},
		{Component: "FieldError", Missing: true},
		{Component: "FieldGroup", Missing: true},
		{Component: "FieldLabel", Missing: true},
		{Component: "FieldLegend", Missing: true},
		{Component: "FieldSet", Missing: true},
	}
}
