// Code generated by gx. DO NOT EDIT.

package icons

import (
	gx "github.com/alternayte/gx"
)

type ChevronDownProps struct {
	// Label is the accessible name of the icon.
	// Empty hides the icon from assistive technology.
	Label string
	// Class adds classes to the root element.
	Class string
}

func ChevronDown(p ChevronDownProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/icons", "ChevronDown", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line ChevronDown.gx:11:1
	_b.Add(gx.Icon("<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"m6 9l6 6l6-6\"/>", gx.IconProps{Label: p.Label, Class: p.Class}))
//line ChevronDown.gx:11:194
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
