// Code generated by gx. DO NOT EDIT.

package icons

import (
	gx "github.com/alternayte/gx"
)

type ChevronRightProps struct {
	// Label is the accessible name of the icon.
	// Empty hides the icon from assistive technology.
	Label string
	// Class adds classes to the root element.
	Class string
}

func ChevronRight(p ChevronRightProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/icons", "ChevronRight", p); _ok {
			return _n
		}
	}
//line ChevronRight.gx:11:1
	return _tChevronRight0.With(
//line ChevronRight.gx:11:1
		gx.Icon("<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"m9 18l6-6l-6-6\"/>", gx.IconProps{Label: p.Label, Class: p.Class}),
	)
}

var _tChevronRight0 = gx.NewTemplate(
	[]string{"", "\n"},
	[]int{0},
	nil,
	[]gx.TemplateRoot{{El: -1, Slot: 0}, {El: -1, Slot: -1}},
)
