// Code generated by gx. DO NOT EDIT.

package sidebar

import (
	gx "github.com/alternayte/gx"
)

type SidebarProps struct {
	Id       string
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func Sidebar(p SidebarProps) gx.Node {
	var _b gx.Builder
//line Sidebar.gx:10:1
	_b.Add(gx.El("aside", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex w-64 shrink-0 flex-col border-r border-border bg-sidebar text-sidebar-foreground", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "id", Value: p.Id, Kind: gx.AttrText}, gx.Bool("data-gx-sidebar", true)}, p.Attrs), p.Children))
//line Sidebar.gx:10:179
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
