// Code generated by gx. DO NOT EDIT.

package sidebar

import (
	gx "github.com/alternayte/gx"
	"github.com/alternayte/gx/examples/shop/ui/button"
	"github.com/alternayte/gx/examples/shop/ui/icons"
)

type SidebarTriggerProps struct {
	Controls string
	Class    string
	Attrs    gx.Attrs
}

func SidebarTrigger(p SidebarTriggerProps) gx.Node {
	var _b gx.Builder
//line SidebarTrigger.gx:14:1
	_b.Add(button.Button(button.ButtonProps{Variant: button.Ghost, Size: button.Icon, Type: "button", Class: gx.Cx("size-7", p.Class), Children: gx.Frag(icons.PanelLeft(icons.PanelLeftProps{Label: "", Class: ""}), gx.El("span", gx.Attrs{gx.Attr{Key: "class", Value: "sr-only", Kind: gx.AttrText}}, gx.Text("Toggle Sidebar"))), Attrs: p.attrs()}))
//line SidebarTrigger.gx:17:17
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
