// Code generated by gx. DO NOT EDIT.

package sidebar

import (
	gx "github.com/alternayte/gx"
)

type SidebarItemProps struct {
	Href     gx.URL
	Active   bool
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func SidebarItem(p SidebarItemProps) gx.Node {
	var _b gx.Builder
//line SidebarItem.gx:11:1
	_b.Add(gx.El("a", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex items-center gap-2 rounded-md px-2 py-1.5 text-sm no-underline transition-colors hover:bg-sidebar-accent hover:text-sidebar-accent-foreground", activeClass[p.Active], p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "href", Value: string(p.Href), Kind: gx.AttrURL, Active: "page"}, gx.Attr{Key: "aria-current", Value: p.current(), Kind: gx.AttrText}}, p.Attrs), p.Children))
//line SidebarItem.gx:11:270
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
