// Code generated by gx. DO NOT EDIT.

package sidebar

import (
	gx "github.com/alternayte/gx"
)

type SidebarFooterProps struct {
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func SidebarFooter(p SidebarFooterProps) gx.Node {
	var _b gx.Builder
//line SidebarFooter.gx:9:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex flex-col gap-2 p-2", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "sidebar-footer", Kind: gx.AttrText}, gx.Attr{Key: "data-sidebar", Value: "footer", Kind: gx.AttrText}}, p.Attrs), p.Children))
//line SidebarFooter.gx:9:136
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
