// Code generated by gx. DO NOT EDIT.

package sidebar

import (
	gx "github.com/alternayte/gx"
)

type SidebarInsetProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the main content of the page.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func SidebarInset(p SidebarInsetProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/sidebar", "SidebarInset", p); _ok {
			return _n
		}
	}
//line SidebarInset.gx:12:1
	return _tSidebarInset0.With(
//line SidebarInset.gx:12:1
		gx.Open("main", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("relative flex w-full flex-1 flex-col bg-background", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "sidebar-inset", Kind: gx.AttrText}}, p.Attrs)),
//line SidebarInset.gx:12:123
		p.Children,
	)
}

var _tSidebarInset0 = gx.NewTemplate(
	[]string{"<main", ">", "</main>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 7}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
