package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// The output paths, relative to the repository root.
const (
	pagesDir  = "docs/content/components"
	indexPage = "docs/content/components.md"
	itemsFile = "docs/registry/items_gen.go"
)

// page is one loaded item with its examples.
type page struct {
	Item     *item
	Examples []*example
}

// buildPages converts every fixture of the registry.
func buildPages(reg *registry) []*page {
	var out []*page
	for _, it := range reg.Items {
		out = append(out, &page{Item: it, Examples: examplesOf(reg, it)})
	}
	return out
}

// render returns every generated file, keyed by its path relative to the
// repository root (REQ-DOC-02).
func render(reg *registry, pages []*page) (map[string][]byte, error) {
	out := map[string][]byte{}
	for _, p := range pages {
		md, err := pageMarkdown(reg, p)
		if err != nil {
			return nil, err
		}
		out[pagesDir+"/"+p.Item.Name+".md"] = []byte(md)
	}
	out[indexPage] = []byte(indexMarkdown(pages))
	src, err := itemsSource(pages)
	if err != nil {
		return nil, err
	}
	out[itemsFile] = src
	return out, nil
}

// quote returns s as a YAML double-quoted scalar and as an attribute value
// of a content tag.
func quote(s string) string {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	_ = enc.Encode(s)
	return strings.TrimSpace(b.String())
}

// attrValue returns s as the quoted value of a content tag attribute. The
// tag scanner has no escape, so a double quote becomes a single quote.
func attrValue(s string) string {
	return `"` + strings.ReplaceAll(strings.Join(strings.Fields(s), " "), `"`, "'") + `"`
}

// pageHref returns the site path of an item page.
func pageHref(name string) string { return "/components/" + name + "/" }

// frontmatter writes the YAML header of a generated page.
func frontmatter(b *strings.Builder, title, description, group, itemName string) {
	b.WriteString("---\n# Generated by docsgen from registry/. Do not edit. Run: just docs-gen\n")
	b.WriteString("title: " + quote(title) + "\n")
	b.WriteString("description: " + quote(description) + "\n")
	if group != "" {
		b.WriteString("group: " + quote(group) + "\n")
	}
	if itemName != "" {
		b.WriteString("item: " + quote(itemName) + "\n")
	}
	b.WriteString("---\n\n")
}

// pageMarkdown returns the content page of one item, in the order of a
// component page: example, installation, usage, examples, do and don't,
// keyboard (REQ-DOC-02).
func pageMarkdown(reg *registry, p *page) (string, error) {
	it := p.Item
	var b strings.Builder
	frontmatter(&b, it.Title, it.Description, it.Group, it.Name)

	switch {
	case it.IconSet:
		fmt.Fprintf(&b, "<IconGrid item=%s />\n\n", attrValue(it.Name))
	case len(p.Examples) > 0:
		if err := writeExample(&b, reg, it, p.Examples[0]); err != nil {
			return "", err
		}
	}
	if it.Server {
		b.WriteString("<docs.Aside kind={docs.Note} title=\"Static preview\">\n\n")
		b.WriteString("This page shows static fixtures. The live behaviour needs a server.\n\n")
		b.WriteString("</docs.Aside>\n\n")
	}

	if err := writeInstallation(&b, reg, it); err != nil {
		return "", err
	}

	if it.Usage.Usage != "" || it.Usage.Intro != "" {
		b.WriteString("## Usage\n\n")
		if it.Usage.Intro != "" && it.Usage.Intro != it.Description {
			b.WriteString(escapeTags(it.Usage.Intro) + "\n\n")
		}
		if it.Usage.Usage != "" {
			b.WriteString(escapeTags(it.Usage.Usage) + "\n\n")
		}
	}
	for _, s := range it.Usage.Other {
		if s.Body == "" {
			continue
		}
		b.WriteString("## " + s.Title + "\n\n" + escapeTags(s.Body) + "\n\n")
	}

	if !it.IconSet && len(p.Examples) > 0 {
		b.WriteString("## Examples\n\n")
		for _, ex := range p.Examples {
			b.WriteString("### " + ex.Title + "\n\n")
			if err := writeExample(&b, reg, it, ex); err != nil {
				return "", err
			}
		}
	}

	if it.Usage.Do != "" || it.Usage.Dont != "" {
		b.WriteString("## Do and don't\n\n<docs.CardGrid>\n")
		if it.Usage.Do != "" {
			b.WriteString("<docs.Card title=\"Do\">\n\n" + escapeTags(it.Usage.Do) + "\n\n</docs.Card>\n")
		}
		if it.Usage.Dont != "" {
			b.WriteString("<docs.Card title=\"Don't\">\n\n" + escapeTags(it.Usage.Dont) + "\n\n</docs.Card>\n")
		}
		b.WriteString("</docs.CardGrid>\n\n")
	}
	if it.Usage.Keyboard != "" {
		b.WriteString("## Keyboard\n\n" + escapeTags(it.Usage.Keyboard) + "\n\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n", nil
}

// writeExample writes one live example: the preview frame and the code of
// its fixtures.
func writeExample(b *strings.Builder, reg *registry, it *item, ex *example) error {
	fmt.Fprintf(b, "<Example item=%s name=%s label=%s", attrValue(it.Name), attrValue(ex.Slug), attrValue(it.Title+": "+ex.Title))
	if it.Kind == "block" {
		b.WriteString(" block")
	}
	b.WriteString(">\n\n")
	var code []string
	for _, part := range ex.Parts {
		code = append(code, part.Snippet.Code)
	}
	if err := writeFence(b, "gx", "", strings.Join(code, "\n")); err != nil {
		return err
	}
	for _, part := range ex.Parts {
		if part.Snippet.Tag {
			continue
		}
		b.WriteString("The code renders the fixture by its name. The fixture sets these props.\n\n")
		rel, err := filepath.Rel(reg.Root, filepath.Join(it.Dir, part.Comp.Name+".fixtures.go"))
		if err != nil {
			return err
		}
		if err := writeFence(b, "go", "title="+attrValue(filepath.ToSlash(rel)), dedent(part.Fixture.Source)); err != nil {
			return err
		}
	}
	b.WriteString("</Example>\n\n")
	return nil
}

// writeFence writes one fenced code block with an info string. The fence is a tilde fence when
// the code holds a backtick fence.
func writeFence(b *strings.Builder, lang, info, code string) error {
	fence := "```"
	ticks, tildes := false, false
	for _, line := range strings.Split(code, "\n") {
		trimmed := strings.TrimSpace(line)
		ticks = ticks || strings.HasPrefix(trimmed, "```")
		tildes = tildes || strings.HasPrefix(trimmed, "~~~")
	}
	if ticks {
		fence = "~~~"
		if tildes {
			return fmt.Errorf("docsgen: a code block holds both fence forms; no Markdown fence can hold it")
		}
	}
	b.WriteString(fence + lang)
	if info != "" {
		b.WriteString(" " + info)
	}
	b.WriteString("\n" + strings.TrimRight(code, "\n") + "\n" + fence + "\n\n")
	return nil
}

// dedent removes the indentation of the closing line from every later
// line, and shows tabs as two spaces.
func dedent(src string) string {
	lines := strings.Split(src, "\n")
	last := lines[len(lines)-1]
	pad := last[:len(last)-len(strings.TrimLeft(last, "\t "))]
	for i := 1; i < len(lines); i++ {
		lines[i] = strings.TrimPrefix(lines[i], pad)
	}
	return strings.ReplaceAll(strings.Join(lines, "\n"), "\t", "  ")
}

// fenceLang maps a file extension to the language of its code block.
func fenceLang(path string) string {
	switch filepath.Ext(path) {
	case ".gx":
		return "gx"
	case ".go":
		return "go"
	case ".css":
		return "css"
	case ".ts":
		return "ts"
	case ".js":
		return "js"
	case ".json":
		return "json"
	case ".md":
		return "md"
	}
	return "text"
}

// writeInstallation writes the installation section: the gx add command,
// the dependencies, the files and the theme tokens, and a manual tab with
// every source file.
func writeInstallation(b *strings.Builder, reg *registry, it *item) error {
	b.WriteString("## Installation\n\n<docs.Tabs sync=\"install\">\n<docs.TabItem label=\"CLI\">\n\n")
	b.WriteString("Run the command in the app module.\n\n")
	if err := writeFence(b, "sh", `frame="terminal" title="Terminal"`, "gx add "+it.Name); err != nil {
		return err
	}
	if len(it.Dependencies) > 0 {
		b.WriteString("The command also installs " + dependencyLinks(reg, it) + ".\n\n")
	}
	if len(it.Files) > 0 {
		b.WriteString("The command writes these files.\n\n| File | Path in the app |\n| --- | --- |\n")
		for _, f := range it.Files {
			fmt.Fprintf(b, "| `%s` | `%s` |\n", f.Path, f.Target)
		}
		b.WriteString("\n")
	}
	b.WriteString("</docs.TabItem>\n<docs.TabItem label=\"Manual\">\n\n")
	if len(it.Dependencies) > 0 {
		b.WriteString("Install " + dependencyLinks(reg, it) + " first.\n\n")
	}
	b.WriteString("Copy each file to its path in the app. Change each import of a registry package to the path of that package in the app.\n\n")
	for _, f := range it.Files {
		src, err := os.ReadFile(filepath.Join(it.Dir, filepath.FromSlash(f.Path)))
		if err != nil {
			return fmt.Errorf("docsgen: item %s lists a file it does not have: %w", it.Name, err)
		}
		if err := writeFence(b, fenceLang(f.Path), "title="+attrValue(f.Target), string(src)); err != nil {
			return err
		}
	}
	b.WriteString("</docs.TabItem>\n</docs.Tabs>\n\n")
	if len(it.Tokens) > 0 {
		tokens := make([]string, len(it.Tokens))
		for i, t := range it.Tokens {
			tokens[i] = "`" + t + "`"
		}
		b.WriteString("The theme must define these tokens: " + strings.Join(tokens, ", ") + ".\n\n")
	}
	return nil
}

// dependencyLinks returns the registry dependencies of an item as links to
// their pages.
func dependencyLinks(reg *registry, it *item) string {
	links := make([]string, len(it.Dependencies))
	for i, dep := range it.Dependencies {
		if _, ok := reg.byName[dep]; ok {
			links[i] = "[`" + dep + "`](" + pageHref(dep) + ")"
		} else {
			links[i] = "`" + dep + "`"
		}
	}
	if len(links) == 1 {
		return links[0]
	}
	return strings.Join(links[:len(links)-1], ", ") + " and " + links[len(links)-1]
}

// escapeTags escapes the component tags of registry prose. The content
// compiler reads a capitalised tag outside code as a component of the
// collection, and usage text names components of other packages.
func escapeTags(md string) string {
	var out strings.Builder
	fence := ""
	for i, line := range strings.Split(md, "\n") {
		if i > 0 {
			out.WriteByte('\n')
		}
		trimmed := strings.TrimSpace(line)
		if fence != "" {
			if strings.HasPrefix(trimmed, fence) {
				fence = ""
			}
			out.WriteString(line)
			continue
		}
		if strings.HasPrefix(trimmed, "```") || strings.HasPrefix(trimmed, "~~~") {
			fence = trimmed[:3]
			out.WriteString(line)
			continue
		}
		out.WriteString(escapeLineTags(line))
	}
	return out.String()
}

// escapeLineTags escapes the component tags of one prose line. Inline code
// stays as written.
func escapeLineTags(line string) string {
	var out strings.Builder
	for i := 0; i < len(line); {
		switch {
		case line[i] == '`':
			run := 0
			for i+run < len(line) && line[i+run] == '`' {
				run++
			}
			end := strings.Index(line[i+run:], strings.Repeat("`", run))
			if end < 0 {
				out.WriteString(line[i:])
				return out.String()
			}
			stop := i + run + end + run
			out.WriteString(line[i:stop])
			i = stop
		case line[i] == '<' && componentTagAt(line[i+1:]):
			out.WriteString("&lt;")
			i++
		default:
			out.WriteByte(line[i])
			i++
		}
	}
	return out.String()
}

// componentTagAt reports whether s, the text after "<", starts a component
// tag name: an optional slash and qualifier, then an upper-case letter.
func componentTagAt(s string) bool {
	s = strings.TrimPrefix(s, "/")
	end := 0
	for end < len(s) && (s[end] == '_' || s[end] == '.' || s[end] == '-' || isAlnum(s[end])) {
		end++
	}
	name := s[:end]
	if dot := strings.LastIndexByte(name, '.'); dot >= 0 {
		name = name[dot+1:]
	}
	return name != "" && name[0] >= 'A' && name[0] <= 'Z'
}

func isAlnum(c byte) bool {
	return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')
}

// indexMarkdown returns the components index: every item under its group,
// with its description and a link to its page (REQ-DOC-02).
func indexMarkdown(pages []*page) string {
	var b strings.Builder
	frontmatter(&b, "Components", "Every item of the Gx registry: components, blocks, the docs kit and icons.", "", "")
	b.WriteString("Each page shows live examples, the example code and the install command. Install an item with `gx add <name>`.\n\n")
	for _, group := range groups {
		var items []*item
		for _, p := range pages {
			if p.Item.Group == group {
				items = append(items, p.Item)
			}
		}
		if len(items) == 0 {
			continue
		}
		b.WriteString("## " + group + "\n\n<docs.CardGrid>\n")
		for _, it := range items {
			fmt.Fprintf(&b, "<docs.LinkCard title=%s description=%s href=%s />\n", attrValue(it.Title), attrValue(it.Description), attrValue(pageHref(it.Name)))
		}
		b.WriteString("</docs.CardGrid>\n\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

// itemsSource returns the Go file that lists every item and renders every
// example in a production build. The dev gallery list has the gxdev build
// tag and cannot ship (REQ-DOC-02).
func itemsSource(pages []*page) ([]byte, error) {
	aliases := map[string]string{} // import path -> alias
	used := map[string]bool{"gx": true}
	var paths []string
	for _, p := range pages {
		if len(p.Examples) == 0 {
			continue
		}
		alias := p.Item.PkgName
		for n := 2; used[alias]; n++ {
			alias = p.Item.PkgName + strconv.Itoa(n)
		}
		used[alias] = true
		aliases[p.Item.PkgPath] = alias
		paths = append(paths, p.Item.PkgPath)
	}
	sort.Strings(paths)

	var b bytes.Buffer
	b.WriteString("// Code generated by docsgen from registry/. DO NOT EDIT.\n\n")
	b.WriteString("package registry\n\nimport (\n\tgx \"github.com/alternayte/gx\"\n")
	for _, path := range paths {
		fmt.Fprintf(&b, "\t%s %q\n", aliases[path], path)
	}
	b.WriteString(")\n\n")
	b.WriteString("// Groups lists the sidebar groups of the items, in sidebar order.\nvar Groups = []string{")
	for i, group := range groups {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(group))
	}
	b.WriteString("}\n\n")
	b.WriteString("// Items lists every registry item in name order, with a render function\n// per example (REQ-DOC-02).\nvar Items = []Item{\n")
	for _, p := range pages {
		it := p.Item
		fmt.Fprintf(&b, "\t{\n\t\tName: %q,\n\t\tTitle: %q,\n\t\tGroup: %q,\n\t\tDescription: %q,\n", it.Name, it.Title, it.Group, it.Description)
		if it.Kind == "block" {
			b.WriteString("\t\tBlock: true,\n")
		}
		if it.IconSet {
			b.WriteString("\t\tIconSet: true,\n")
		}
		if len(p.Examples) > 0 {
			b.WriteString("\t\tExamples: []Example{\n")
			alias := aliases[it.PkgPath]
			for _, ex := range p.Examples {
				var fixtures, calls []string
				for _, part := range ex.Parts {
					fixtures = append(fixtures, strconv.Quote(part.Comp.Name+"/"+part.Fixture.Name))
					call := fmt.Sprintf("%s.%s(%s.%s[%q])", alias, part.Comp.Name, alias, part.Comp.FixturesVar, part.Fixture.Name)
					if part.Comp.Wrap != "" {
						call = fmt.Sprintf("%s.%s(%s)", alias, part.Comp.Wrap, call)
					}
					calls = append(calls, call)
				}
				node := calls[0]
				if len(calls) > 1 {
					node = "gx.Frag(" + strings.Join(calls, ", ") + ")"
				}
				fmt.Fprintf(&b, "\t\t\t{Name: %q, Title: %q, Component: %q, Fixtures: []string{%s}, Node: func() gx.Node { return %s }},\n",
					ex.Slug, ex.Title, ex.Parts[0].Comp.Name, strings.Join(fixtures, ", "), node)
			}
			b.WriteString("\t\t},\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("docsgen: the items file does not format: %w", err)
	}
	return src, nil
}
