// Code generated by gx. DO NOT EDIT.

package card

import (
	gx "github.com/alternayte/gx"
)

type CardProps struct {
	// Title is the heading of the card. An empty value renders no heading.
	Title string
	// Description is the text below the title. An empty value renders no description.
	Description string
	// Action is a control shown at the top right of the card header. A nil value renders no action.
	Action gx.Node
	// Footer is the content of the card footer. A nil value renders no footer.
	Footer gx.Node
	// Class adds classes to the root element.
	Class string
	// Children is the content of the card.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func Card(p CardProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/card", "Card", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line Card.gx:20:1
	var _b1 gx.Builder
//line Card.gx:20:158
	_b1.Add(_tCard0)
//line Card.gx:21:3
	if p.Title != "" || p.Description != "" || p.Action != nil {
//line Card.gx:21:63
		_b1.Add(_tCard1)
//line Card.gx:22:5
		var _b2 gx.Builder
//line Card.gx:22:195
		_b2.Add(_tCard2)
//line Card.gx:23:7
		if p.Title != "" {
//line Card.gx:23:25
			_b2.Add(_tCard3.With(
//line Card.gx:24:9
				gx.Open("h3", gx.Attrs{gx.Attr{Key: "class", Value: "leading-none font-semibold", Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "card-title", Kind: gx.AttrText}}),
//line Card.gx:24:71
				gx.Text(p.Title),
			))
		}
//line Card.gx:25:8
		_b2.Add(_tCard2)
//line Card.gx:26:7
		if p.Description != "" {
//line Card.gx:26:31
			_b2.Add(_tCard4.With(
//line Card.gx:27:9
				gx.Open("p", gx.Attrs{gx.Attr{Key: "class", Value: "text-sm text-muted-foreground", Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "card-description", Kind: gx.AttrText}}),
//line Card.gx:27:79
				gx.Text(p.Description),
			))
		}
//line Card.gx:28:8
		_b2.Add(_tCard2)
//line Card.gx:29:7
		if p.Action != nil {
//line Card.gx:29:27
			_b2.Add(_tCard5.With(
//line Card.gx:30:9
				gx.Open("div", gx.Attrs{gx.Attr{Key: "class", Value: "col-start-2 row-span-2 row-start-1 self-start justify-self-end", Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "card-action", Kind: gx.AttrText}}),
//line Card.gx:30:109
				p.Action,
			))
		}
//line Card.gx:31:8
		_b2.Add(_tCard1)
//line Card.gx:22:5
		_b1.Add(_tCard6.With(
//line Card.gx:22:5
			gx.Open("div", gx.Attrs{gx.Attr{Key: "class", Value: "@container/card-header grid auto-rows-min grid-rows-[auto_auto] items-start gap-2 px-6 has-data-[slot=card-action]:grid-cols-[1fr_auto] [.border-b]:pb-6", Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "card-header", Kind: gx.AttrText}}),
//line Card.gx:22:5
			_b2.Node(),
		))
	}
//line Card.gx:33:4
	_b1.Add(_tCard0)
//line Card.gx:34:3
	if p.Children != nil {
//line Card.gx:34:25
		_b1.Add(_tCard7.With(
//line Card.gx:35:5
			gx.Open("div", gx.Attrs{gx.Attr{Key: "class", Value: "px-6", Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "card-content", Kind: gx.AttrText}}),
//line Card.gx:35:48
			p.Children,
		))
	}
//line Card.gx:36:4
	_b1.Add(_tCard0)
//line Card.gx:37:3
	if p.Footer != nil {
//line Card.gx:37:23
		_b1.Add(_tCard7.With(
//line Card.gx:38:5
			gx.Open("div", gx.Attrs{gx.Attr{Key: "class", Value: "flex items-center px-6 [.border-t]:pt-6", Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "card-footer", Kind: gx.AttrText}}),
//line Card.gx:38:82
			p.Footer,
		))
	}
//line Card.gx:39:4
	_b1.Add(_tCard8)
//line Card.gx:20:1
	_b.Add(_tCard9.With(
//line Card.gx:20:1
		gx.Open("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex flex-col gap-6 rounded-xl border border-border bg-card py-6 text-card-foreground shadow-sm", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "card", Kind: gx.AttrText}}, p.Attrs)),
//line Card.gx:20:1
		_b1.Node(),
	))
	return _b.Node()
}

var _tCard0 = gx.NewTemplate(
	[]string{"\n  "},
	[]int{},
	nil,
	[]gx.TemplateRoot{{El: -1, Slot: -1}},
).With()

var _tCard1 = gx.NewTemplate(
	[]string{"\n    "},
	[]int{},
	nil,
	[]gx.TemplateRoot{{El: -1, Slot: -1}},
).With()

var _tCard2 = gx.NewTemplate(
	[]string{"\n      "},
	[]int{},
	nil,
	[]gx.TemplateRoot{{El: -1, Slot: -1}},
).With()

var _tCard3 = gx.NewTemplate(
	[]string{"\n        <h3", ">", "</h3>\n      "},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 9, EndStatic: 2, End: 5}},
	[]gx.TemplateRoot{{El: -1, Slot: -1}, {El: 0, Slot: -1}, {El: -1, Slot: -1}},
)

var _tCard4 = gx.NewTemplate(
	[]string{"\n        <p", ">", "</p>\n      "},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 9, EndStatic: 2, End: 4}},
	[]gx.TemplateRoot{{El: -1, Slot: -1}, {El: 0, Slot: -1}, {El: -1, Slot: -1}},
)

var _tCard5 = gx.NewTemplate(
	[]string{"\n        <div", ">", "</div>\n      "},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 9, EndStatic: 2, End: 6}},
	[]gx.TemplateRoot{{El: -1, Slot: -1}, {El: 0, Slot: -1}, {El: -1, Slot: -1}},
)

var _tCard6 = gx.NewTemplate(
	[]string{"<div", ">", "</div>\n  "},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 6}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)

var _tCard7 = gx.NewTemplate(
	[]string{"\n    <div", ">", "</div>\n  "},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 5, EndStatic: 2, End: 6}},
	[]gx.TemplateRoot{{El: -1, Slot: -1}, {El: 0, Slot: -1}, {El: -1, Slot: -1}},
)

var _tCard8 = gx.NewTemplate(
	[]string{"\n"},
	[]int{},
	nil,
	[]gx.TemplateRoot{{El: -1, Slot: -1}},
).With()

var _tCard9 = gx.NewTemplate(
	[]string{"<div", ">", "</div>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 6}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
