// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package gxdev_gallery

import (
	gx "github.com/alternayte/gx"
	badge "github.com/alternayte/gx/registry/badge"
)

// Fixtures returns every component fixture for the dev gallery
// (REQ-AI-03).
func Fixtures() []gx.Fixture {
	return []gx.Fixture{
		{Component: "Badge", Name: "Default", Node: func() gx.Node { return badge.Badge(badge.BadgeFixtures["Default"]) }},
		{Component: "Badge", Name: "Destructive", Node: func() gx.Node { return badge.Badge(badge.BadgeFixtures["Destructive"]) }},
		{Component: "Badge", Name: "Outline", Node: func() gx.Node { return badge.Badge(badge.BadgeFixtures["Outline"]) }},
		{Component: "Badge", Name: "Secondary", Node: func() gx.Node { return badge.Badge(badge.BadgeFixtures["Secondary"]) }},
	}
}
