// Code generated by gx. DO NOT EDIT.

package radiogroup

import (
	gx "github.com/alternayte/gx"
	"github.com/alternayte/gx/examples/shop/ui/icons"
)

type RadioGroupItemProps struct {
	// Name is the form field name. Every item of one group has the same name.
	Name string
	// Value is the value the form submits when the item is checked.
	Value string
	// Checked selects the item for the first render.
	Checked bool
	// Disabled disables the item.
	Disabled bool
	// Invalid sets aria-invalid on the input and shows the error style.
	Invalid bool
	// Label is the text beside the radio. An empty value renders no text.
	Label string
	// Class adds classes to the root element.
	Class string
	// Children is content beside the radio, after the label text.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func RadioGroupItem(p RadioGroupItemProps) gx.Node {
	var _b gx.Builder
//line RadioGroupItem.gx:26:1
	var _b1 gx.Builder
//line RadioGroupItem.gx:26:116
	_b1.Add(gx.Text("\n  "))
//line RadioGroupItem.gx:27:3
	_b1.Add(gx.El("input", gx.Attrs{gx.Attr{Key: "class", Value: "peer sr-only", Kind: gx.AttrText}, gx.Attr{Key: "type", Value: "radio", Kind: gx.AttrText}, gx.Attr{Key: "name", Value: p.Name, Kind: gx.AttrText}, gx.Attr{Key: "value", Value: p.Value, Kind: gx.AttrText}, gx.Bool("checked", p.Checked), gx.Bool("disabled", p.Disabled), gx.Attr{Key: "aria-invalid", Value: p.invalid(), Kind: gx.AttrText}}))
//line RadioGroupItem.gx:27:145
	_b1.Add(gx.Text("\n  "))
//line RadioGroupItem.gx:28:3
	_b1.Add(gx.El("span", gx.Attrs{gx.Attr{Key: "class", Value: "relative aspect-square size-4 shrink-0 rounded-full border border-input text-primary shadow-xs transition-[color,box-shadow] outline-none peer-focus-visible:border-ring peer-focus-visible:ring-[3px] peer-focus-visible:ring-ring/50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50 peer-aria-invalid:border-destructive peer-aria-invalid:ring-destructive/20 dark:bg-input/30 dark:peer-aria-invalid:ring-destructive/40 motion-reduce:transition-none [&>svg]:opacity-0 peer-checked:[&>svg]:opacity-100", Kind: gx.AttrText}, gx.Attr{Key: "aria-hidden", Value: "true", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n    "), icons.Circle(icons.CircleProps{Label: "", Class: "absolute top-1/2 left-1/2 size-2 -translate-x-1/2 -translate-y-1/2 [&>circle]:fill-primary"}), gx.Text("\n  "))))
//line RadioGroupItem.gx:30:10
	_b1.Add(gx.Text("\n  "))
//line RadioGroupItem.gx:31:3
	if p.Label != "" {
//line RadioGroupItem.gx:31:21
		_b1.Add(gx.Text("\n    "))
//line RadioGroupItem.gx:32:5
		_b1.Add(gx.El("span", gx.Attrs{gx.Attr{Key: "class", Value: "peer-disabled:cursor-not-allowed peer-disabled:opacity-50", Kind: gx.AttrText}}, gx.Text(p.Label)))
//line RadioGroupItem.gx:32:93
		_b1.Add(gx.Text("\n  "))
	}
//line RadioGroupItem.gx:33:4
	_b1.Add(gx.Text("\n  "))
//line RadioGroupItem.gx:34:3
	if p.Children != nil {
//line RadioGroupItem.gx:34:25
		_b1.Add(gx.Text("\n    "))
//line RadioGroupItem.gx:35:5
		_b1.Add(gx.El("span", gx.Attrs{gx.Attr{Key: "class", Value: "peer-disabled:cursor-not-allowed peer-disabled:opacity-50", Kind: gx.AttrText}}, p.Children))
//line RadioGroupItem.gx:35:96
		_b1.Add(gx.Text("\n  "))
	}
//line RadioGroupItem.gx:36:4
	_b1.Add(gx.Text("\n"))
	_b.Add(gx.El("label", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex items-center gap-2 text-sm leading-none font-medium select-none", p.Class), Kind: gx.AttrText}}, p.Attrs), _b1.Node()))
//line RadioGroupItem.gx:37:9
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
