// Code generated by gx. DO NOT EDIT.

package popover

import (
	gx "github.com/alternayte/gx"
)

type PopoverTitleProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the text of the title.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func PopoverTitle(p PopoverTitleProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/popover", "PopoverTitle", p); _ok {
			return _n
		}
	}
//line PopoverTitle.gx:12:1
	return _tPopoverTitle0.With(
//line PopoverTitle.gx:12:1
		gx.Open("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("font-medium", p.Class), Kind: gx.AttrText}}, p.Attrs)),
//line PopoverTitle.gx:12:57
		p.Children,
	)
}

var _tPopoverTitle0 = gx.NewTemplate(
	[]string{"<div", ">", "</div>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 6}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
