// Code generated by gx. DO NOT EDIT.

package popover

import (
	gx "github.com/alternayte/gx"
)

type PopoverHeaderProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the content of the header, usually a title and a description.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func PopoverHeader(p PopoverHeaderProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/popover", "PopoverHeader", p); _ok {
			return _n
		}
	}
//line PopoverHeader.gx:12:1
	return _tPopoverHeader0.With(
//line PopoverHeader.gx:12:1
		gx.Open("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex flex-col gap-1 text-sm", p.Class), Kind: gx.AttrText}}, p.Attrs)),
//line PopoverHeader.gx:12:73
		p.Children,
	)
}

var _tPopoverHeader0 = gx.NewTemplate(
	[]string{"<div", ">", "</div>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 6}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
