// Code generated by gx. DO NOT EDIT.

package popover

import (
	gx "github.com/alternayte/gx"
	"github.com/alternayte/gx/registry/button"
)

type PopoverTriggerProps struct {
	Id       string
	Variant  button.Variant
	Size     button.Size
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func PopoverTrigger(p PopoverTriggerProps) gx.Node {
	var _b gx.Builder
//line PopoverTrigger.gx:14:1
	_b.Add(button.Button(button.ButtonProps{Variant: p.variant(), Size: p.Size, Type: "button", Class: p.Class, Children: p.Children, Attrs: p.attrs()}))
//line PopoverTrigger.gx:14:114
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
