// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package radiogroup

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/registry/radio-group",
		Name: "radiogroup",
		Values: map[string]reflect.Value{
			"Horizontal":             reflect.ValueOf(Horizontal),
			"RadioGroup":             reflect.ValueOf(RadioGroup),
			"RadioGroupFixtures":     reflect.ValueOf(&RadioGroupFixtures).Elem(),
			"RadioGroupItem":         reflect.ValueOf(RadioGroupItem),
			"RadioGroupItemFixtures": reflect.ValueOf(&RadioGroupItemFixtures).Elem(),
			"Vertical":               reflect.ValueOf(Vertical),
			"orientationClass":       reflect.ValueOf(&orientationClass).Elem(),
		},
		Types: map[string]reflect.Type{
			"Orientation":         reflect.TypeFor[Orientation](),
			"RadioGroupItemProps": reflect.TypeFor[RadioGroupItemProps](),
			"RadioGroupProps":     reflect.TypeFor[RadioGroupProps](),
		},
		Methods: map[string]reflect.Value{
			"RadioGroupItemProps.invalid": reflect.ValueOf(RadioGroupItemProps.invalid),
			"RadioGroupProps.orientation": reflect.ValueOf(RadioGroupProps.orientation),
		},
	}
}

var _ constant.Value
