// Code generated by gx. DO NOT EDIT.

package radiogroup

import (
	gx "github.com/alternayte/gx"
)

type RadioGroupProps struct {
	// Orientation sets the layout direction: Vertical or Horizontal.
	Orientation Orientation
	// Label is the accessible name of the group.
	Label string
	// Class adds classes to the root element.
	Class string
	// Children is the radio items.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func RadioGroup(p RadioGroupProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/radio-group", "RadioGroup", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line RadioGroup.gx:16:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("grid gap-3", orientationClass[p.orientation()], p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "role", Value: "radiogroup", Kind: gx.AttrText}, gx.Attr{Key: "aria-label", Value: p.Label, Kind: gx.AttrText}, gx.Attr{Key: "aria-orientation", Value: string(p.orientation()), Kind: gx.AttrText}}, p.Attrs), p.Children))
//line RadioGroup.gx:16:183
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
