// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package gxdev_gallery

import (
	gx "github.com/alternayte/gx"
	label "github.com/alternayte/gx/registry/label"
)

// Fixtures returns every component fixture for the dev gallery
// (REQ-AI-03).
func Fixtures() []gx.Fixture {
	return []gx.Fixture{
		{Component: "Label", Name: "Plain", Node: func() gx.Node { return label.Label(label.LabelFixtures["Plain"]) }},
	}
}
