// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package drawer

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/examples/shop/ui/drawer",
		Name: "drawer",
		Values: map[string]reflect.Value{
			"Bottom":         reflect.ValueOf(Bottom),
			"Drawer":         reflect.ValueOf(Drawer),
			"DrawerFixtures": reflect.ValueOf(&DrawerFixtures).Elem(),
			"Left":           reflect.ValueOf(Left),
			"Right":          reflect.ValueOf(Right),
			"Top":            reflect.ValueOf(Top),
			"sideClass":      reflect.ValueOf(&sideClass).Elem(),
		},
		Types: map[string]reflect.Type{
			"DrawerProps": reflect.TypeFor[DrawerProps](),
			"Side":        reflect.TypeFor[Side](),
		},
		Methods: map[string]reflect.Value{
			"DrawerProps.side":      reflect.ValueOf(DrawerProps.side),
			"DrawerProps.sideClass": reflect.ValueOf(DrawerProps.sideClass),
		},
	}
}

var _ constant.Value
