// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package gxdev_gallery

import (
	gx "github.com/alternayte/gx"
	alert "github.com/alternayte/gx/registry/alert"
)

// Fixtures returns every component fixture for the dev gallery
// (REQ-AI-03).
func Fixtures() []gx.Fixture {
	return []gx.Fixture{
		{Component: "Alert", Name: "Default", Node: func() gx.Node { return alert.Alert(alert.AlertFixtures["Default"]) }},
		{Component: "Alert", Name: "Destructive", Node: func() gx.Node { return alert.Alert(alert.AlertFixtures["Destructive"]) }},
	}
}
