// Code generated by gx. DO NOT EDIT.

package navigationmenu

import (
	gx "github.com/alternayte/gx"
)

type NavigationMenuItemProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is one link, or one trigger with its content.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func NavigationMenuItem(p NavigationMenuItemProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/navigation-menu", "NavigationMenuItem", p); _ok {
			return _n
		}
	}
//line NavigationMenuItem.gx:12:1
	return _tNavigationMenuItem0.With(
//line NavigationMenuItem.gx:12:1
		gx.Open("li", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("group/navigation-menu-item relative", p.Class), Kind: gx.AttrText}}, p.Attrs)),
//line NavigationMenuItem.gx:12:80
		p.Children,
	)
}

var _tNavigationMenuItem0 = gx.NewTemplate(
	[]string{"<li", ">", "</li>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 5}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
