// Code generated by gx. DO NOT EDIT.

package dropdownmenu

import (
	gx "github.com/alternayte/gx"
)

type DropdownMenuSubContentProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the list of items of the sub-menu.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func DropdownMenuSubContent(p DropdownMenuSubContentProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/dropdown-menu", "DropdownMenuSubContent", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line DropdownMenuSubContent.gx:12:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("z-50 min-w-[8rem] overflow-hidden rounded-md border border-border bg-popover p-1 text-popover-foreground shadow-lg outline-hidden", subMotionClass, p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "popover", Value: "auto", Kind: gx.AttrText}, gx.Attr{Key: "role", Value: "menu", Kind: gx.AttrText}, gx.Attr{Key: "data-gx-roving", Value: "nowrap", Kind: gx.AttrText}, gx.Attr{Key: "data-gx-place", Value: "right start", Kind: gx.AttrText}}, p.Attrs), p.Children))
//line DropdownMenuSubContent.gx:12:288
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
