// Code generated by gx. DO NOT EDIT.

package dropdownmenu

import (
	gx "github.com/alternayte/gx"
)

type DropdownMenuLinkProps struct {
	Href     gx.URL
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func DropdownMenuLink(p DropdownMenuLinkProps) gx.Node {
	var _b gx.Builder
//line DropdownMenuLink.gx:10:1
	_b.Add(gx.El("a", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-sm no-underline outline-none select-none hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "role", Value: "menuitem", Kind: gx.AttrText}, gx.Attr{Key: "tabindex", Value: "-1", Kind: gx.AttrText}, gx.Attr{Key: "href", Value: string(p.Href), Kind: gx.AttrURL, Active: "page"}, gx.Bool("data-gx-roving-item", true), gx.Bool("data-gx-close", true)}, p.Attrs), p.Children))
//line DropdownMenuLink.gx:10:327
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
