// Code generated by gx. DO NOT EDIT.

package dropdownmenu

import (
	gx "github.com/alternayte/gx"
)

type DropdownMenuProps struct {
	// Id is the id of the root element. The trigger opens the menu by this id.
	Id string
	// Align sets the edge of the trigger that the menu lines up with: Center, Start or End.
	Align Align
	// Class adds classes to the root element.
	Class string
	// Children is the menu items.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func DropdownMenu(p DropdownMenuProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/dropdown-menu", "DropdownMenu", p); _ok {
			return _n
		}
	}
//line DropdownMenu.gx:16:1
	return _tDropdownMenu0.With(
//line DropdownMenu.gx:16:1
		gx.Open("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("z-50 min-w-[8rem] overflow-x-hidden overflow-y-auto rounded-md border border-border bg-popover p-1 text-popover-foreground shadow-md outline-hidden", motionClass, alignClass[p.align()], p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "style", Value: string(gx.StyleJoin(gx.Style(p.style()))), Kind: gx.AttrStyle}}, gx.Attrs{gx.Attr{Key: "id", Value: p.Id, Kind: gx.AttrText}, gx.Attr{Key: "popover", Value: "auto", Kind: gx.AttrText}, gx.Attr{Key: "role", Value: "menu", Kind: gx.AttrText}, gx.Bool("data-gx-dismiss", true), gx.Attr{Key: "data-gx-roving", Value: "nowrap", Kind: gx.AttrText}, gx.Attr{Key: "data-gx-place", Value: p.place(), Kind: gx.AttrText}}, p.Attrs)),
//line DropdownMenu.gx:16:350
		p.Children,
	)
}

var _tDropdownMenu0 = gx.NewTemplate(
	[]string{"<div", ">", "</div>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 6}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
