// Code generated by gx. DO NOT EDIT.

package progress

import (
	gx "github.com/alternayte/gx"
)

type ProgressProps struct {
	Value int
	Max   int
	Label string
	Class string
	Attrs gx.Attrs
}

func Progress(p ProgressProps) gx.Node {
	var _b gx.Builder
//line Progress.gx:11:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("bg-primary/20 relative h-2 w-full overflow-hidden rounded-full", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "role", Value: "progressbar", Kind: gx.AttrText}, gx.Attr{Key: "aria-valuemin", Value: gx.TextValue(0), Kind: gx.AttrText}, gx.Attr{Key: "aria-valuemax", Value: gx.TextValue(p.max()), Kind: gx.AttrText}, gx.Attr{Key: "aria-valuenow", Value: gx.TextValue(p.Value), Kind: gx.AttrText}, gx.Attr{Key: "aria-label", Value: p.Label, Kind: gx.AttrText}}, p.Attrs), gx.Frag(gx.Text("\n  "), gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "bg-primary h-full w-full flex-1", Kind: gx.AttrText}, gx.Attr{Key: "style", Value: string(gx.StyleJoin(gx.Style(gx.Style("transform: translateX(-" + p.offset() + "%)")))), Kind: gx.AttrStyle}}), gx.Text("\n"))))
//line Progress.gx:13:7
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
