// Code generated by gx. DO NOT EDIT.

package icons

import (
	gx "github.com/alternayte/gx"
)

type CheckProps struct {
	// Label is the accessible name of the icon.
	// Empty hides the icon from assistive technology.
	Label string
	// Class adds classes to the root element.
	Class string
}

func Check(p CheckProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/icons", "Check", p); _ok {
			return _n
		}
	}
//line Check.gx:11:1
	return _tCheck0.With(
//line Check.gx:11:1
		gx.Icon("<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M20 6L9 17l-5-5\"/>", gx.IconProps{Label: p.Label, Class: p.Class}),
	)
}

var _tCheck0 = gx.NewTemplate(
	[]string{"", "\n"},
	[]int{0},
	nil,
	[]gx.TemplateRoot{{El: -1, Slot: 0}, {El: -1, Slot: -1}},
)
