// Code generated by gx. DO NOT EDIT.

package icons

import (
	gx "github.com/alternayte/gx"
)

type ChevronUpProps struct {
	// Label is the accessible name of the icon.
	// Empty hides the icon from assistive technology.
	Label string
	// Class adds classes to the root element.
	Class string
}

func ChevronUp(p ChevronUpProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/icons", "ChevronUp", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line ChevronUp.gx:11:1
	_b.Add(gx.Icon("<path fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"m18 15l-6-6l-6 6\"/>", gx.IconProps{Label: p.Label, Class: p.Class}))
//line ChevronUp.gx:11:198
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
