// Code generated by gx. DO NOT EDIT.

package icons

import (
	gx "github.com/alternayte/gx"
)

type CircleProps struct {
	Label string
	Class string
}

func Circle(p CircleProps) gx.Node {
	var _b gx.Builder
//line Circle.gx:8:1
	_b.Add(gx.Icon("<circle cx=\"12\" cy=\"12\" r=\"10\" fill=\"none\" stroke=\"currentColor\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\"/>", gx.IconProps{Label: p.Label, Class: p.Class}))
//line Circle.gx:8:206
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
