// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package table

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/examples/shop/ui/table",
		Name: "table",
		Values: map[string]reflect.Value{
			"Table":                reflect.ValueOf(Table),
			"TableBody":            reflect.ValueOf(TableBody),
			"TableBodyFixtures":    reflect.ValueOf(&TableBodyFixtures).Elem(),
			"TableCaption":         reflect.ValueOf(TableCaption),
			"TableCaptionFixtures": reflect.ValueOf(&TableCaptionFixtures).Elem(),
			"TableCell":            reflect.ValueOf(TableCell),
			"TableCellFixtures":    reflect.ValueOf(&TableCellFixtures).Elem(),
			"TableFixtures":        reflect.ValueOf(&TableFixtures).Elem(),
			"TableFooter":          reflect.ValueOf(TableFooter),
			"TableFooterFixtures":  reflect.ValueOf(&TableFooterFixtures).Elem(),
			"TableHead":            reflect.ValueOf(TableHead),
			"TableHeadFixtures":    reflect.ValueOf(&TableHeadFixtures).Elem(),
			"TableHeader":          reflect.ValueOf(TableHeader),
			"TableHeaderFixtures":  reflect.ValueOf(&TableHeaderFixtures).Elem(),
			"TableRow":             reflect.ValueOf(TableRow),
			"TableRowFixtures":     reflect.ValueOf(&TableRowFixtures).Elem(),
			"invoiceHead":          reflect.ValueOf(invoiceHead),
			"invoiceRows":          reflect.ValueOf(invoiceRows),
		},
		Types: map[string]reflect.Type{
			"TableBodyProps":    reflect.TypeFor[TableBodyProps](),
			"TableCaptionProps": reflect.TypeFor[TableCaptionProps](),
			"TableCellProps":    reflect.TypeFor[TableCellProps](),
			"TableFooterProps":  reflect.TypeFor[TableFooterProps](),
			"TableHeadProps":    reflect.TypeFor[TableHeadProps](),
			"TableHeaderProps":  reflect.TypeFor[TableHeaderProps](),
			"TableProps":        reflect.TypeFor[TableProps](),
			"TableRowProps":     reflect.TypeFor[TableRowProps](),
		},
	}
}

var _ constant.Value
