// Code generated by gx. DO NOT EDIT.

package table

import (
	gx "github.com/alternayte/gx"
)

type TableFooterProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the rows of the footer.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func TableFooter(p TableFooterProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/table", "TableFooter", p); _ok {
			return _n
		}
	}
//line TableFooter.gx:12:1
	return _tTableFooter0.With(
//line TableFooter.gx:12:1
		gx.Open("tfoot", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("border-t bg-muted/50 font-medium [&>tr]:last:border-b-0", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "table-footer", Kind: gx.AttrText}}, p.Attrs)),
//line TableFooter.gx:12:128
		p.Children,
	)
}

var _tTableFooter0 = gx.NewTemplate(
	[]string{"<tfoot", ">", "</tfoot>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 8}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
