// Code generated by gx. DO NOT EDIT.

package table

import (
	gx "github.com/alternayte/gx"
)

type TableHeaderProps struct {
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func TableHeader(p TableHeaderProps) gx.Node {
	var _b gx.Builder
//line TableHeader.gx:9:1
	_b.Add(gx.El("thead", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("[&_tr]:border-b", p.Class), Kind: gx.AttrText}}, p.Attrs), p.Children))
//line TableHeader.gx:9:83
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
