// Code generated by gx. DO NOT EDIT.

package table

import (
	gx "github.com/alternayte/gx"
)

type TableRowProps struct {
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func TableRow(p TableRowProps) gx.Node {
	var _b gx.Builder
//line TableRow.gx:9:1
	_b.Add(gx.El("tr", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("border-b border-border transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted", p.Class), Kind: gx.AttrText}}, p.Attrs), p.Children))
//line TableRow.gx:9:151
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
