// Code generated by gx. DO NOT EDIT.

package menubar

import (
	gx "github.com/alternayte/gx"
)

type MenubarSubContentProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the list of items of the sub-menu.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func MenubarSubContent(p MenubarSubContentProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/menubar", "MenubarSubContent", p); _ok {
			return _n
		}
	}
//line MenubarSubContent.gx:12:1
	return _tMenubarSubContent0.With(
//line MenubarSubContent.gx:12:1
		gx.Open("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("z-50 min-w-[8rem] overflow-hidden rounded-md border border-border bg-popover p-1 text-popover-foreground shadow-lg outline-hidden", subMotionClass, p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "popover", Value: "auto", Kind: gx.AttrText}, gx.Attr{Key: "role", Value: "menu", Kind: gx.AttrText}, gx.Attr{Key: "data-gx-roving", Value: "nowrap", Kind: gx.AttrText}, gx.Attr{Key: "data-gx-place", Value: "right start", Kind: gx.AttrText}}, p.Attrs)),
//line MenubarSubContent.gx:12:270
		p.Children,
	)
}

var _tMenubarSubContent0 = gx.NewTemplate(
	[]string{"<div", ">", "</div>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 6}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
