// Code generated by gx. DO NOT EDIT.

package menubar

import (
	gx "github.com/alternayte/gx"
)

type MenubarItemProps struct {
	Href     gx.URL
	Active   bool
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func MenubarItem(p MenubarItemProps) gx.Node {
	var _b gx.Builder
//line MenubarItem.gx:11:1
	_b.Add(gx.El("a", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("inline-flex items-center rounded-sm px-2 py-1 text-sm font-medium no-underline outline-none hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground", activeClass[p.Active], p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "role", Value: "menuitem", Kind: gx.AttrText}, gx.Attr{Key: "tabindex", Value: "-1", Kind: gx.AttrText}, gx.Attr{Key: "href", Value: string(p.Href), Kind: gx.AttrURL, Active: "page"}, gx.Bool("data-gx-roving-item", true), gx.Attr{Key: "aria-current", Value: p.current(), Kind: gx.AttrText}}, p.Attrs), p.Children))
//line MenubarItem.gx:11:355
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
