// Code generated by gx. DO NOT EDIT.

package selectbox

import (
	gx "github.com/alternayte/gx"
)

type SelectSeparatorProps struct {
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func SelectSeparator(p SelectSeparatorProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/select", "SelectSeparator", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line SelectSeparator.gx:8:1
	_b.Add(gx.El("hr", p.Attrs))
//line SelectSeparator.gx:8:20
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
