// Code generated by gx. DO NOT EDIT.

package selectbox

import (
	gx "github.com/alternayte/gx"
)

type SelectGroupProps struct {
	Label    string
	Disabled bool
	Children gx.Node
}

func SelectGroup(p SelectGroupProps) gx.Node {
	var _b gx.Builder
//line SelectGroup.gx:9:1
	_b.Add(gx.El("optgroup", gx.Attrs{gx.Attr{Key: "label", Value: p.Label, Kind: gx.AttrText}, gx.Bool("disabled", p.Disabled)}, p.Children))
//line SelectGroup.gx:9:72
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
