// Code generated by gx. DO NOT EDIT.

package inputgroup

import (
	gx "github.com/alternayte/gx"
	"github.com/alternayte/gx/examples/shop/ui/textarea"
)

type InputGroupTextareaProps struct {
	// Id is the id of the root element. A label points at it.
	Id string
	// Name is the name attribute. The form sends the value under this name.
	Name string
	// Value is the start text of the textarea.
	Value string
	// Placeholder is the placeholder attribute: the hint text of an empty control.
	Placeholder string
	// Class adds classes to the root element.
	Class string
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func InputGroupTextarea(p InputGroupTextareaProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/input-group", "InputGroupTextarea", p); _ok {
			return _n
		}
	}
//line InputGroupTextarea.gx:20:1
	return _tInputGroupTextarea0.With(
//line InputGroupTextarea.gx:20:1
		gx.Open("textarea", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx(textarea.Control, "flex-1 resize-none rounded-none border-0 bg-transparent py-3 shadow-none focus-visible:ring-0 dark:bg-transparent", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "name", Value: p.Name, Kind: gx.AttrText}, gx.Attr{Key: "placeholder", Value: p.Placeholder, Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "input-group-control", Kind: gx.AttrText}}, p.attrs())),
//line InputGroupTextarea.gx:20:258
		gx.Text(p.Value),
	)
}

var _tInputGroupTextarea0 = gx.NewTemplate(
	[]string{"<textarea", ">", "</textarea>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 11}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
