// Code generated by gx. DO NOT EDIT.

package chart

import (
	gx "github.com/alternayte/gx"
)

type ChartProps struct {
	// Id is the id of the root element.
	Id string
	// Title is the caption of the chart and its accessible name.
	Title string
	// Kind sets the drawing: Bar, Line or Area.
	Kind Kind
	// Categories are the labels of the horizontal axis, in order.
	Categories []string
	// Series are the rows of numbers: one value for each category.
	Series []Series
	// Class adds classes to the root element.
	Class string
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func Chart(p ChartProps) gx.Node {
	var _b gx.Builder
//line Chart.gx:20:1
	var _b1 gx.Builder
//line Chart.gx:20:84
	_b1.Add(gx.Text("\n  "))
//line Chart.gx:21:3
	_b1.Add(gx.El("figcaption", gx.Attrs{gx.Attr{Key: "class", Value: captionClass, Kind: gx.AttrText}}, gx.Text(p.Title)))
//line Chart.gx:21:58
	_b1.Add(gx.Text("\n  "))
//line Chart.gx:22:3
	_b1.Add(ChartCanvas(ChartCanvasProps{Table: p.tableID(), Label: p.Title, Kind: string(p.kind()), Categories: p.Categories, Series: p.Series, Classes: canvasClasses}))
//line Chart.gx:22:146
	_b1.Add(gx.Text("\n  "))
//line Chart.gx:23:3
	var _b2 gx.Builder
//line Chart.gx:23:46
	_b2.Add(gx.Text("\n    "))
//line Chart.gx:24:5
	var _b3 gx.Builder
//line Chart.gx:24:12
	_b3.Add(gx.Text("\n      "))
//line Chart.gx:25:7
	var _b4 gx.Builder
//line Chart.gx:25:11
	_b4.Add(gx.Text("\n        "))
//line Chart.gx:26:9
	_b4.Add(gx.El("th", gx.Attrs{gx.Attr{Key: "class", Value: cellClass, Kind: gx.AttrText}, gx.Attr{Key: "scope", Value: "col", Kind: gx.AttrText}}, gx.Text(p.Title)))
//line Chart.gx:26:57
	_b4.Add(gx.Text("\n        "))
//line Chart.gx:27:9
	for _, c := range p.Categories {
//line Chart.gx:27:41
		_b4.Add(gx.Text("\n          "))
//line Chart.gx:28:11
		_b4.Add(gx.El("th", gx.Attrs{gx.Attr{Key: "class", Value: cellClass, Kind: gx.AttrText}, gx.Attr{Key: "scope", Value: "col", Kind: gx.AttrText}}, gx.Text(c)))
//line Chart.gx:28:53
		_b4.Add(gx.Text("\n        "))
	}
//line Chart.gx:29:10
	_b4.Add(gx.Text("\n      "))
	_b3.Add(gx.El("tr", nil, _b4.Node()))
//line Chart.gx:30:12
	_b3.Add(gx.Text("\n    "))
	_b2.Add(gx.El("thead", nil, _b3.Node()))
//line Chart.gx:31:13
	_b2.Add(gx.Text("\n    "))
//line Chart.gx:32:5
	var _b5 gx.Builder
//line Chart.gx:32:12
	_b5.Add(gx.Text("\n      "))
//line Chart.gx:33:7
	for _, s := range p.Series {
//line Chart.gx:33:35
		_b5.Add(gx.Text("\n        "))
//line Chart.gx:34:9
		var _b6 gx.Builder
//line Chart.gx:34:13
		_b6.Add(gx.Text("\n          "))
//line Chart.gx:35:11
		_b6.Add(gx.El("th", gx.Attrs{gx.Attr{Key: "class", Value: cellClass, Kind: gx.AttrText}, gx.Attr{Key: "scope", Value: "row", Kind: gx.AttrText}}, gx.Text(s.Name)))
//line Chart.gx:35:58
		_b6.Add(gx.Text("\n          "))
//line Chart.gx:36:11
		for _, v := range s.Values {
//line Chart.gx:36:39
			_b6.Add(gx.Text("\n            "))
//line Chart.gx:37:13
			_b6.Add(gx.El("td", gx.Attrs{gx.Attr{Key: "class", Value: cellClass, Kind: gx.AttrText}}, gx.Text(formatValue(v))))
//line Chart.gx:37:56
			_b6.Add(gx.Text("\n          "))
		}
//line Chart.gx:38:12
		_b6.Add(gx.Text("\n        "))
		_b5.Add(gx.El("tr", nil, _b6.Node()))
//line Chart.gx:39:14
		_b5.Add(gx.Text("\n      "))
	}
//line Chart.gx:40:8
	_b5.Add(gx.Text("\n    "))
	_b2.Add(gx.El("tbody", nil, _b5.Node()))
//line Chart.gx:41:13
	_b2.Add(gx.Text("\n  "))
	_b1.Add(gx.El("table", gx.Attrs{gx.Attr{Key: "class", Value: tableClass, Kind: gx.AttrText}, gx.Attr{Key: "id", Value: p.tableID(), Kind: gx.AttrText}}, _b2.Node()))
//line Chart.gx:42:11
	_b1.Add(gx.Text("\n"))
	_b.Add(gx.El("figure", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx(rootClass, p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "id", Value: p.Id, Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "chart", Kind: gx.AttrText}}, p.Attrs), _b1.Node()))
//line Chart.gx:43:10
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
