// Code generated by gx. DO NOT EDIT.

package field

import (
	gx "github.com/alternayte/gx"
)

type FieldTitleProps struct {
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func FieldTitle(p FieldTitleProps) gx.Node {
	var _b gx.Builder
//line FieldTitle.gx:9:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex w-fit items-center gap-2 text-sm leading-snug font-medium group-data-[disabled=true]/field:opacity-50", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "field-label", Kind: gx.AttrText}}, p.Attrs), p.Children))
//line FieldTitle.gx:9:194
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
