// Code generated by gx. DO NOT EDIT.

package togglegroup

import (
	gx "github.com/alternayte/gx"
)

type ToggleGroupProps struct {
	Variant  Variant
	Size     Size
	Spacing  int
	Label    string
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func ToggleGroup(p ToggleGroupProps) gx.Node {
	var _b gx.Builder
//line ToggleGroup.gx:13:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("group/toggle-group flex w-fit items-center gap-[--spacing(var(--gap))] rounded-md", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "style", Value: string(gx.StyleJoin(gx.Style(p.gap()))), Kind: gx.AttrStyle}}, gx.Attrs{gx.Attr{Key: "role", Value: "group", Kind: gx.AttrText}, gx.Attr{Key: "aria-label", Value: p.Label, Kind: gx.AttrText}, gx.Attr{Key: "data-variant", Value: p.variant(), Kind: gx.AttrText}, gx.Attr{Key: "data-size", Value: p.size(), Kind: gx.AttrText}, gx.Attr{Key: "data-spacing", Value: gx.TextValue(p.spacing()), Kind: gx.AttrText}}, p.Attrs), p.Children))
//line ToggleGroup.gx:13:270
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
