// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package settingsform

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/examples/shop/ui/settings-form",
		Name: "settingsform",
		Values: map[string]reflect.Value{
			"SettingsForm":         reflect.ValueOf(SettingsForm),
			"SettingsFormFixtures": reflect.ValueOf(&SettingsFormFixtures).Elem(),
		},
		Types: map[string]reflect.Type{
			"SettingsFormProps": reflect.TypeFor[SettingsFormProps](),
		},
	}
}

var _ constant.Value
