// Code generated by gx. DO NOT EDIT.

package empty

import (
	gx "github.com/alternayte/gx"
)

type EmptyDescriptionProps struct {
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func EmptyDescription(p EmptyDescriptionProps) gx.Node {
	var _b gx.Builder
//line EmptyDescription.gx:9:1
	_b.Add(gx.El("p", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("text-sm text-muted-foreground [&>a]:underline [&>a]:underline-offset-4 [&>a:hover]:text-primary", p.Class), Kind: gx.AttrText}}, p.Attrs), p.Children))
//line EmptyDescription.gx:9:155
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
