// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package pagination

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/registry/pagination",
		Name: "pagination",
		Values: map[string]reflect.Value{
			"Pagination":                 reflect.ValueOf(Pagination),
			"PaginationContent":          reflect.ValueOf(PaginationContent),
			"PaginationContentFixtures":  reflect.ValueOf(&PaginationContentFixtures).Elem(),
			"PaginationEllipsis":         reflect.ValueOf(PaginationEllipsis),
			"PaginationEllipsisFixtures": reflect.ValueOf(&PaginationEllipsisFixtures).Elem(),
			"PaginationFixtures":         reflect.ValueOf(&PaginationFixtures).Elem(),
			"PaginationItem":             reflect.ValueOf(PaginationItem),
			"PaginationItemFixtures":     reflect.ValueOf(&PaginationItemFixtures).Elem(),
			"PaginationItemWrap":         reflect.ValueOf(PaginationItemWrap),
			"PaginationLink":             reflect.ValueOf(PaginationLink),
			"PaginationLinkFixtures":     reflect.ValueOf(&PaginationLinkFixtures).Elem(),
			"PaginationNext":             reflect.ValueOf(PaginationNext),
			"PaginationNextFixtures":     reflect.ValueOf(&PaginationNextFixtures).Elem(),
			"PaginationPrevious":         reflect.ValueOf(PaginationPrevious),
			"PaginationPreviousFixtures": reflect.ValueOf(&PaginationPreviousFixtures).Elem(),
		},
		Types: map[string]reflect.Type{
			"PaginationContentProps":  reflect.TypeFor[PaginationContentProps](),
			"PaginationEllipsisProps": reflect.TypeFor[PaginationEllipsisProps](),
			"PaginationItemProps":     reflect.TypeFor[PaginationItemProps](),
			"PaginationLinkProps":     reflect.TypeFor[PaginationLinkProps](),
			"PaginationNextProps":     reflect.TypeFor[PaginationNextProps](),
			"PaginationPreviousProps": reflect.TypeFor[PaginationPreviousProps](),
			"PaginationProps":         reflect.TypeFor[PaginationProps](),
		},
		Methods: map[string]reflect.Value{
			"PaginationLinkProps.attrs":     reflect.ValueOf(PaginationLinkProps.attrs),
			"PaginationLinkProps.class":     reflect.ValueOf(PaginationLinkProps.class),
			"PaginationNextProps.attrs":     reflect.ValueOf(PaginationNextProps.attrs),
			"PaginationPreviousProps.attrs": reflect.ValueOf(PaginationPreviousProps.attrs),
		},
	}
}

var _ constant.Value
