// Code generated by gx. DO NOT EDIT.

package pagination

import (
	gx "github.com/alternayte/gx"
)

type PaginationContentProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the pagination items.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func PaginationContent(p PaginationContentProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/pagination", "PaginationContent", p); _ok {
			return _n
		}
	}
//line PaginationContent.gx:12:1
	return _tPaginationContent0.With(
//line PaginationContent.gx:12:1
		gx.Open("ul", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex flex-row items-center gap-1", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "pagination-content", Kind: gx.AttrText}}, p.Attrs)),
//line PaginationContent.gx:12:108
		p.Children,
	)
}

var _tPaginationContent0 = gx.NewTemplate(
	[]string{"<ul", ">", "</ul>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 5}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
