// Code generated by gx. DO NOT EDIT.

package pagination

import (
	gx "github.com/alternayte/gx"
	"github.com/alternayte/gx/registry/button"
	"github.com/alternayte/gx/registry/icons"
)

type PaginationPreviousProps struct {
	// Href is the URL of the previous page.
	Href gx.URL
	// Class adds classes to the root element.
	Class string
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func PaginationPrevious(p PaginationPreviousProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/pagination", "PaginationPrevious", p); _ok {
			return _n
		}
	}
//line PaginationPrevious.gx:15:1
	return _tPaginationPrevious1.With(
//line PaginationPrevious.gx:15:1
		PaginationLink(PaginationLinkProps{Href: p.Href, Active: false, Size: button.Md, Class: gx.Cx("gap-1 px-2.5 sm:pl-2.5", p.Class), Children: _tPaginationPrevious0.With(
//line PaginationPrevious.gx:16:3
			icons.ChevronLeft(icons.ChevronLeftProps{Label: "", Class: ""}),
		), Attrs: p.attrs()}),
	)
}

var _tPaginationPrevious0 = gx.NewTemplate(
	[]string{"", "<span class=\"hidden sm:block\">Previous</span>"},
	[]int{0},
	nil,
	[]gx.TemplateRoot{{El: -1, Slot: 0}, {El: -1, Slot: -1, Name: "span"}},
)

var _tPaginationPrevious1 = gx.NewTemplate(
	[]string{"", "\n"},
	[]int{0},
	nil,
	[]gx.TemplateRoot{{El: -1, Slot: 0}, {El: -1, Slot: -1}},
)
