// Code generated by gx. DO NOT EDIT.

package route

import (
	"fmt"
	gx "github.com/alternayte/gx"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// Pattern returns the method and pattern of Page.
func (Page) Pattern() string { return "GET /dashboard" }

// Bind fills Page from the request.
func (in *Page) Bind(r *http.Request) error {
	return nil
}

// URL returns the path of Page.
func (in Page) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("dashboard")
	return gx.BasePath() + b.String()
}

// Pattern returns the method and pattern of Refresh.
func (Refresh) Pattern() string { return "POST /dashboard/refresh" }

// Bind fills Refresh from the request.
func (in *Refresh) Bind(r *http.Request) error {
	if v := r.URL.Query().Get("round"); v != "" {
		x, err := strconv.ParseInt(v, 10, 0)
		if err != nil {
			return fmt.Errorf("gx: Round: %w", err)
		}
		in.Round = int(x)
	}
	return nil
}

// URL returns the path of Refresh.
func (in Refresh) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("dashboard")
	b.WriteString("/")
	b.WriteString("refresh")
	q := url.Values{}
	if in.Round != 0 {
		q.Set("round", strconv.FormatInt(int64(in.Round), 10))
	}
	if s := q.Encode(); s != "" {
		b.WriteString("?")
		b.WriteString(s)
	}
	return gx.BasePath() + b.String()
}
