// Code generated by gx. DO NOT EDIT.

package resizable

import (
	gx "github.com/alternayte/gx"
)

// ResizableDrag renders the island of ResizableDrag.ts (REQ-ISL-01). The browser mounts it
// with the props as JSON. An option sets the time of the load.
func ResizableDrag(p ResizableDragProps, opts ...gx.IslandOption) gx.Node {
	return gx.Island("github.com/alternayte/gx/examples/shop/ui/resizable/ResizableDrag", string(_gxResizableDragJSON0(make([]byte, 0, 256), p)), opts...)
}

func _gxResizableDragJSON0(b []byte, v ResizableDragProps) []byte {
	b = append(b, "{\"handle\":"...)
	b = gx.AppendJSONString(b, string(v.Handle))
	b = append(b, ",\"step\":"...)
	b = gx.AppendJSONInt(b, int64(v.Step))
	b = append(b, ",\"gripClass\":"...)
	b = gx.AppendJSONString(b, string(v.GripClass))
	b = append(b, '}')
	return b
}
