// Code generated by gx. DO NOT EDIT.

package resizable

import (
	gx "github.com/alternayte/gx"
)

type ResizablePanelProps struct {
	// Size is the first size of the panel, in percent of the group. A zero value shares the free space.
	Size int
	// MinSize is the smallest size of the panel, in percent of the group.
	MinSize int
	// MaxSize is the largest size of the panel, in percent of the group. A zero value is 100.
	MaxSize int
	// Class adds classes to the content element inside the panel.
	Class string
	// Children is the content of the panel.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func ResizablePanel(p ResizablePanelProps) gx.Node {
	var _b gx.Builder
//line ResizablePanel.gx:18:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: panelClass, Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "style", Value: string(gx.StyleJoin(gx.Style(p.style()))), Kind: gx.AttrStyle}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "resizable-panel", Kind: gx.AttrText}, gx.Attr{Key: "data-min-size", Value: gx.TextValue(p.MinSize), Kind: gx.AttrText}, gx.Attr{Key: "data-max-size", Value: gx.TextValue(p.maxSize()), Kind: gx.AttrText}}, p.Attrs), gx.Frag(gx.Text("\n  "), gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx(contentClass, p.Class), Kind: gx.AttrText}}, p.Children), gx.Text("\n"))))
//line ResizablePanel.gx:20:7
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
