// Code generated by gx. DO NOT EDIT.

package ui

import (
	gx "github.com/alternayte/gx"
)

type CheckboxProps struct {
	Field    gx.FieldView
	Children gx.Node
}

func Checkbox(p CheckboxProps) gx.Node {
	var _b gx.Builder
//line Checkbox.gx:8:1
	var _b1 gx.Builder
//line Checkbox.gx:8:20
	_b1.Add(gx.Text("\n  "))
//line Checkbox.gx:9:3
	_b1.Add(gx.El("label", nil, gx.Frag(gx.Text("\n    "), gx.El("input", gx.JoinAttrs(p.Field.Attrs(), gx.Attrs{gx.Attr{Key: "type", Value: "checkbox", Kind: gx.AttrText}})), gx.Text("\n    "), p.Children, gx.Text("\n  "))))
//line Checkbox.gx:12:11
	_b1.Add(gx.Text("\n  "))
//line Checkbox.gx:13:3
	if p.Field.FieldError() != "" {
//line Checkbox.gx:13:34
		_b1.Add(gx.Text("\n    "))
//line Checkbox.gx:14:5
		_b1.Add(gx.El("p", gx.Attrs{gx.Attr{Key: "id", Value: p.Field.FieldID() + "-error", Kind: gx.AttrText}, gx.Attr{Key: "role", Value: "alert", Kind: gx.AttrText}}, gx.Text(p.Field.FieldError())))
//line Checkbox.gx:14:81
		_b1.Add(gx.Text("\n  "))
	}
//line Checkbox.gx:15:4
	_b1.Add(gx.Text("\n"))
	_b.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "field", Kind: gx.AttrText}}, _b1.Node()))
//line Checkbox.gx:16:7
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
