// Code generated by gx. DO NOT EDIT.

package ui

import (
	gx "github.com/alternayte/gx"
)

type TextFieldProps struct {
	Field    gx.FieldView
	Label    string
	Type     string
	Validate string
}

func TextField(p TextFieldProps) gx.Node {
	var _b gx.Builder
//line TextField.gx:10:1
	_b.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "field", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n  "), gx.El("label", gx.Attrs{gx.Attr{Key: "for", Value: p.Field.FieldID(), Kind: gx.AttrText}}, gx.Text(p.Label)), gx.Text("\n  "), gx.El("input", gx.JoinAttrs(p.Field.Attrs(), gx.Attrs{gx.Attr{Key: "type", Value: p.Field.FieldInputType(p.Type), Kind: gx.AttrText}, gx.Attr{Key: "data-gx-validate", Value: p.Validate, Kind: gx.AttrText}})), gx.Text("\n  "), gx.El("p", gx.Attrs{gx.Attr{Key: "id", Value: p.Field.FieldID() + "-error", Kind: gx.AttrText}, gx.Attr{Key: "role", Value: "alert", Kind: gx.AttrText}}, gx.Text(p.Field.FieldError())), gx.Text("\n"))))
//line TextField.gx:14:7
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
