// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package combobox

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/examples/shop/ui/combobox",
		Name: "combobox",
		Values: map[string]reflect.Value{
			"Combobox":         reflect.ValueOf(Combobox),
			"ComboboxFixtures": reflect.ValueOf(&ComboboxFixtures).Elem(),
			"ComboboxInput":    reflect.ValueOf(ComboboxInput),
			"frameworks":       reflect.ValueOf(&frameworks).Elem(),
			"inputClasses":     reflect.ValueOf(&inputClasses).Elem(),
		},
		Consts: map[string]constant.Value{
			"rootClass":   gx.DevString("relative inline-block w-64"),
			"selectClass": gx.DevString("h-9 w-full rounded-md border border-input bg-transparent px-3 text-base shadow-xs outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 md:text-sm dark:bg-input/30"),
		},
		Types: map[string]reflect.Type{
			"ComboboxInputProps": reflect.TypeFor[ComboboxInputProps](),
			"ComboboxProps":      reflect.TypeFor[ComboboxProps](),
			"InputClasses":       reflect.TypeFor[InputClasses](),
			"Option":             reflect.TypeFor[Option](),
		},
		Methods: map[string]reflect.Value{
			"ComboboxProps.emptyText":   reflect.ValueOf(ComboboxProps.emptyText),
			"ComboboxProps.placeholder": reflect.ValueOf(ComboboxProps.placeholder),
		},
	}
}

var _ constant.Value
