// Code generated by gx. DO NOT EDIT.

package breadcrumb

import (
	gx "github.com/alternayte/gx"
)

type BreadcrumbLinkProps struct {
	// Href is the URL of the link.
	Href gx.URL
	// Class adds classes to the root element.
	Class string
	// Children is the link label.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func BreadcrumbLink(p BreadcrumbLinkProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/breadcrumb", "BreadcrumbLink", p); _ok {
			return _n
		}
	}
//line BreadcrumbLink.gx:14:1
	return _tBreadcrumbLink0.With(
//line BreadcrumbLink.gx:14:1
		gx.Open("a", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("transition-colors hover:text-foreground", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "href", Value: string(p.Href), Kind: gx.AttrURL, Active: "page"}, gx.Attr{Key: "data-slot", Value: "breadcrumb-link", Kind: gx.AttrText}}, p.Attrs)),
//line BreadcrumbLink.gx:14:125
		p.Children,
	)
}

var _tBreadcrumbLink0 = gx.NewTemplate(
	[]string{"<a", ">", "</a>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 4}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
