// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package datepicker

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/registry/date-picker",
		Name: "datepicker",
		Values: map[string]reflect.Value{
			"DatePicker":         reflect.ValueOf(DatePicker),
			"DatePickerFixtures": reflect.ValueOf(&DatePickerFixtures).Elem(),
		},
		Consts: map[string]constant.Value{
			"displayClass": gx.DevString("truncate data-[empty=true]:text-muted-foreground"),
			"triggerClass": gx.DevString("w-64 justify-start font-normal"),
		},
		Types: map[string]reflect.Type{
			"DatePickerProps": reflect.TypeFor[DatePickerProps](),
		},
		Methods: map[string]reflect.Value{
			"DatePickerProps.displayID": reflect.ValueOf(DatePickerProps.displayID),
			"DatePickerProps.empty":     reflect.ValueOf(DatePickerProps.empty),
			"DatePickerProps.popoverID": reflect.ValueOf(DatePickerProps.popoverID),
			"DatePickerProps.text":      reflect.ValueOf(DatePickerProps.text),
		},
	}
}

var _ constant.Value
