// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package gxdev_gallery

import (
	gx "github.com/alternayte/gx"
	buttongroup "github.com/alternayte/gx/registry/button-group"
)

// Fixtures returns every component fixture for the dev gallery
// (REQ-AI-03).
func Fixtures() []gx.Fixture {
	return []gx.Fixture{
		{Component: "ButtonGroup", Name: "Three", Node: func() gx.Node { return buttongroup.ButtonGroup(buttongroup.ButtonGroupFixtures["Three"]) }},
	}
}
