// Code generated by gx. DO NOT EDIT.

package alert

import (
	gx "github.com/alternayte/gx"
)

type AlertProps struct {
	// Variant sets the tone: Default or Destructive.
	Variant Variant
	// Title is the heading of the alert. An empty value renders no heading.
	Title string
	// Icon is an svg icon shown in the column before the text. A nil value renders no icon column.
	Icon gx.Node
	// Class adds classes to the root element.
	Class string
	// Children is the content of the alert description. A nil value renders no description.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func Alert(p AlertProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/alert", "Alert", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line Alert.gx:18:1
	var _b1 gx.Builder
//line Alert.gx:18:68
	_b1.Add(gx.Text("\n  "))
//line Alert.gx:19:3
	if p.Icon != nil {
//line Alert.gx:19:21
		_b1.Add(gx.Text("\n    "))
//line Alert.gx:20:5
		_b1.Add(p.Icon)
//line Alert.gx:20:13
		_b1.Add(gx.Text("\n  "))
	}
//line Alert.gx:21:4
	_b1.Add(gx.Text("\n  "))
//line Alert.gx:22:3
	if p.Title != "" {
//line Alert.gx:22:21
		_b1.Add(gx.Text("\n    "))
//line Alert.gx:23:5
		_b1.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "col-start-2 line-clamp-1 min-h-4 font-medium tracking-tight", Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "alert-title", Kind: gx.AttrText}}, gx.Text(p.Title)))
//line Alert.gx:23:117
		_b1.Add(gx.Text("\n  "))
	}
//line Alert.gx:24:4
	_b1.Add(gx.Text("\n  "))
//line Alert.gx:25:3
	if p.Children != nil {
//line Alert.gx:25:25
		_b1.Add(gx.Text("\n    "))
//line Alert.gx:26:5
		_b1.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "col-start-2 grid justify-items-start gap-1 text-sm text-muted-foreground [&_p]:leading-relaxed", Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "alert-description", Kind: gx.AttrText}}, p.Children))
//line Alert.gx:26:161
		_b1.Add(gx.Text("\n  "))
	}
//line Alert.gx:27:4
	_b1.Add(gx.Text("\n"))
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: p.class(), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "alert", Kind: gx.AttrText}, gx.Attr{Key: "role", Value: "alert", Kind: gx.AttrText}}, p.Attrs), _b1.Node()))
//line Alert.gx:28:7
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
