// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package alert

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/examples/shop/ui/alert",
		Name: "alert",
		Values: map[string]reflect.Value{
			"Alert":         reflect.ValueOf(Alert),
			"AlertFixtures": reflect.ValueOf(&AlertFixtures).Elem(),
			"Default":       reflect.ValueOf(Default),
			"Destructive":   reflect.ValueOf(Destructive),
			"variantClass":  reflect.ValueOf(&variantClass).Elem(),
		},
		Types: map[string]reflect.Type{
			"AlertProps": reflect.TypeFor[AlertProps](),
			"Variant":    reflect.TypeFor[Variant](),
		},
		Methods: map[string]reflect.Value{
			"AlertProps.class": reflect.ValueOf(AlertProps.class),
		},
	}
}

var _ constant.Value
