// Code generated by gx. DO NOT EDIT.

package sidebar

import (
	gx "github.com/alternayte/gx"
)

type SidebarSeparatorProps struct {
	// Class adds classes to the root element.
	Class string
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func SidebarSeparator(p SidebarSeparatorProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/sidebar", "SidebarSeparator", p); _ok {
			return _n
		}
	}
//line SidebarSeparator.gx:10:1
	return _tSidebarSeparator0.With(
//line SidebarSeparator.gx:10:1
		gx.Open("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("h-px w-full shrink-0 bg-border", "mx-2 w-auto bg-sidebar-border", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "sidebar-separator", Kind: gx.AttrText}, gx.Attr{Key: "data-sidebar", Value: "separator", Kind: gx.AttrText}, gx.Attr{Key: "role", Value: "none", Kind: gx.AttrText}, gx.Attr{Key: "data-orientation", Value: "horizontal", Kind: gx.AttrText}}, p.Attrs)),
	)
}

var _tSidebarSeparator0 = gx.NewTemplate(
	[]string{"<div", "></div>\n"},
	[]int{0},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 1, End: 7}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
