// Code generated by gx. DO NOT EDIT.

package sidebar

import (
	gx "github.com/alternayte/gx"
)

type SidebarMenuSubItemProps struct {
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func SidebarMenuSubItem(p SidebarMenuSubItemProps) gx.Node {
	var _b gx.Builder
//line SidebarMenuSubItem.gx:9:1
	_b.Add(gx.El("li", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("group/menu-sub-item relative", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "sidebar-menu-sub-item", Kind: gx.AttrText}, gx.Attr{Key: "data-sidebar", Value: "menu-sub-item", Kind: gx.AttrText}}, p.Attrs), p.Children))
//line SidebarMenuSubItem.gx:9:153
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
