// Code generated by gx. DO NOT EDIT.

package shell

import (
	gx "github.com/alternayte/gx"
)

type NotFoundProps struct {
	// Title is the heading of the page.
	Title string
	// Message is the text below the title.
	Message string
	// Home is the target of the Go home link.
	Home string
}

func NotFound(p NotFoundProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/docs-shell", "NotFound", p); _ok {
			return _n
		}
	}
//line NotFound.gx:12:1
	return _tNotFound0.With(
//line NotFound.gx:14:43
		gx.Text(p.Title),
//line NotFound.gx:15:41
		gx.Text(p.Message),
//line NotFound.gx:16:3
		gx.Open("a", gx.Attrs{gx.Attr{Key: "class", Value: "mt-6 inline-flex items-center rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground", Kind: gx.AttrText}, gx.Attr{Key: "href", Value: string(gx.URL(p.Home)), Kind: gx.AttrURL, Active: "page"}}),
	)
}

var _tNotFound0 = gx.NewTemplate(
	[]string{"<div class=\"gx-not-found mx-auto my-16 max-w-lg text-center\">\n  <p class=\"text-5xl font-bold\">404</p>\n  <h1 class=\"mt-4 text-2xl font-semibold\">", "</h1>\n  <p class=\"mt-2 text-muted-foreground\">", "</p>\n  <a", ">Go home</a>\n</div>\n"},
	[]int{2, 2, 1},
	[]gx.TemplateEl{{Slot: 2, Start: 7, EndStatic: 3, End: 12}},
	[]gx.TemplateRoot{{El: -1, Slot: -1, Name: "div"}, {El: -1, Slot: -1}},
)
