// Code generated by gx. DO NOT EDIT.

package docs

import (
	gx "github.com/alternayte/gx"
)

type BadgeProps struct {
	// Label is the text of the badge.
	Label string
	// Variant sets the visual style: BadgeDefault, BadgeSecondary, BadgeDestructive or
	// BadgeOutline.
	Variant BadgeVariant
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func Badge(p BadgeProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/docs", "Badge", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line Badge.gx:13:1
	_b.Add(gx.El("span", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-medium", badgeClass[p.Variant]), Kind: gx.AttrText}}, p.Attrs), gx.Text(p.Label)))
//line Badge.gx:13:155
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
