// Code generated by gx. DO NOT EDIT.

package docs

import (
	gx "github.com/alternayte/gx"
)

type LinkCardProps struct {
	Href        gx.URL
	Title       string
	Description string
	Children    gx.Node
	Attrs       gx.Attrs
}

func LinkCard(p LinkCardProps) gx.Node {
	var _b gx.Builder
//line LinkCard.gx:11:1
	var _b1 gx.Builder
//line LinkCard.gx:11:146
	_b1.Add(gx.Text("\n  "))
//line LinkCard.gx:12:3
	_b1.Add(gx.El("span", gx.Attrs{gx.Attr{Key: "class", Value: "block font-medium text-foreground", Kind: gx.AttrText}}, gx.Text(p.Title)))
//line LinkCard.gx:12:67
	_b1.Add(gx.Text("\n  "))
//line LinkCard.gx:13:3
	if p.Description != "" {
//line LinkCard.gx:13:27
		_b1.Add(gx.Text("\n    "))
//line LinkCard.gx:14:5
		_b1.Add(gx.El("span", gx.Attrs{gx.Attr{Key: "class", Value: "mt-1 block text-sm text-muted-foreground", Kind: gx.AttrText}}, gx.Text(p.Description)))
//line LinkCard.gx:14:82
		_b1.Add(gx.Text("\n  "))
	}
//line LinkCard.gx:15:4
	_b1.Add(gx.Text("\n  "))
//line LinkCard.gx:16:3
	if p.Children != nil {
//line LinkCard.gx:16:25
		_b1.Add(gx.Text("\n    "))
//line LinkCard.gx:17:5
		_b1.Add(gx.El("span", gx.Attrs{gx.Attr{Key: "class", Value: "gx-link-card-body mt-2 block text-sm", Kind: gx.AttrText}}, p.Children))
//line LinkCard.gx:17:75
		_b1.Add(gx.Text("\n  "))
	}
//line LinkCard.gx:18:4
	_b1.Add(gx.Text("\n"))
	_b.Add(gx.El("a", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: "gx-link-card my-4 block rounded-lg border border-border p-4 no-underline transition-colors hover:bg-accent", Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "href", Value: string(p.Href), Kind: gx.AttrURL, Active: "page"}}, p.Attrs), _b1.Node()))
//line LinkCard.gx:19:5
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
