// Code generated by gx. DO NOT EDIT.

package tabs

import (
	gx "github.com/alternayte/gx"
)

type TabsProps struct {
	// Orientation sets the layout direction: Horizontal or Vertical. Vertical puts the list beside
	// the panels.
	Orientation Orientation
	// Sync is a key that tab groups share. Groups with the same key keep one selection and remember
	// it per viewer.
	Sync string
	// Default is the label of the tab that is selected first. An empty value selects the first tab.
	Default string
	// Class adds classes to the root element.
	Class string
	// Children is the tab list and the panels.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func Tabs(p TabsProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/tabs", "Tabs", p); _ok {
			return _n
		}
	}
//line Tabs.gx:20:1
	return _tTabs0.With(
//line Tabs.gx:20:1
		gx.Open("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("group/tabs flex gap-2 data-[orientation=horizontal]:flex-col", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Bool("data-gx-tabs", true), gx.Attr{Key: "data-orientation", Value: p.orientation(), Kind: gx.AttrText}, gx.Attr{Key: "data-sync", Value: p.Sync, Kind: gx.AttrText}, gx.Attr{Key: "data-default", Value: p.Default, Kind: gx.AttrText}}, p.Attrs)),
//line Tabs.gx:20:198
		p.Children,
	)
}

var _tTabs0 = gx.NewTemplate(
	[]string{"<div", ">", "</div>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 6}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
