// Code generated by gx. DO NOT EDIT.

package shop

import (
	gx "github.com/alternayte/gx"
	"github.com/alternayte/gx/examples/shop/cart"
	cartroute "github.com/alternayte/gx/examples/shop/cart/route"
)

type HomeProps struct {
	GxKey gx.Key
}

func Home(p HomeProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop", "Home", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line Home.gx:8:1
	_b.Add(gx.Head(gx.HeadProps{Title: "Gx shop home", Meta: nil, Links: nil, Lang: "", HtmlClass: "", BodyClass: ""}))
//line Home.gx:8:33
	_b.Add(gx.Text("\n"))
//line Home.gx:9:1
	_b.Add(gx.El("h1", gx.Attrs{gx.Attr{Key: "class", Value: "text-2xl font-semibold", Kind: gx.AttrText}}, gx.Text("Two carts")))
//line Home.gx:9:50
	_b.Add(gx.Text("\n"))
//line Home.gx:10:1
	_b.Add(cart.Cart(cart.CartProps{Label: "Alpha", Total: 1, GxKey: gx.InstanceKey("alpha")}))
//line Home.gx:10:50
	_b.Add(gx.Text("\n"))
//line Home.gx:11:1
	_b.Add(cart.Cart(cart.CartProps{Label: "Beta", Total: 2, GxKey: gx.InstanceKey("beta")}))
//line Home.gx:11:48
	_b.Add(gx.Text("\n"))
//line Home.gx:12:1
	_b.Add(cart.Toasts(cart.ToastsProps{Class: ""}))
//line Home.gx:12:16
	_b.Add(gx.Text("\n"))
//line Home.gx:13:1
	_b.Add(gx.El("div", gx.Attrs{gx.On("visible", "GET", (cartroute.Lazy{}).URL(), gx.ScopeString("shop.Home", p.GxKey))}, gx.Frag(gx.Text("\n  "), gx.El("span", gx.Attrs{gx.Attr{Key: "id", Value: "lazy-slot", Kind: gx.AttrText}}, gx.Text("waiting")), gx.Text("\n"))))
//line Home.gx:15:7
	_b.Add(gx.Text("\n"))
//line Home.gx:16:1
	_b.Add(gx.El("img", gx.Attrs{gx.Attr{Key: "style", Value: string(gx.StyleJoin(gx.TransitionStyle(Hero(1)))), Kind: gx.AttrStyle}, gx.Attr{Key: "id", Value: "hero", Kind: gx.AttrText}, gx.Attr{Key: "width", Value: "40", Kind: gx.AttrText}, gx.Attr{Key: "height", Value: "40", Kind: gx.AttrText}, gx.Attr{Key: "alt", Value: "Hero", Kind: gx.AttrText}, gx.Attr{Key: "src", Value: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='40' height='40'%3E%3Crect width='40' height='40' fill='%23888'/%3E%3C/svg%3E", Kind: gx.AttrURL}}))
//line Home.gx:16:224
	_b.Add(gx.Text("\n"))
//line Home.gx:17:1
	_b.Add(gx.El("button", gx.Attrs{gx.On("click", "POST", (cartroute.Transition{}).URL(), gx.ScopeString("shop.Home", p.GxKey))}, gx.Text("Transition")))
//line Home.gx:17:62
	_b.Add(gx.Text("\n"))
//line Home.gx:18:1
	_b.Add(gx.El("span", gx.Attrs{gx.Attr{Key: "id", Value: "transition-target", Kind: gx.AttrText}}, gx.Text("idle")))
//line Home.gx:18:41
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
