// Code generated by gx. DO NOT EDIT.

package selectbox

import (
	gx "github.com/alternayte/gx"
)

type SelectGroupProps struct {
	// Label is the visible name of the option group.
	Label string
	// Disabled disables every option of the group.
	Disabled bool
	// Children is the options of the group.
	Children gx.Node
}

func SelectGroup(p SelectGroupProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/select", "SelectGroup", p); _ok {
			return _n
		}
	}
//line SelectGroup.gx:12:1
	return _tSelectGroup0.With(
//line SelectGroup.gx:12:1
		gx.Open("optgroup", gx.Attrs{gx.Attr{Key: "label", Value: p.Label, Kind: gx.AttrText}, gx.Bool("disabled", p.Disabled)}),
//line SelectGroup.gx:12:49
		p.Children,
	)
}

var _tSelectGroup0 = gx.NewTemplate(
	[]string{"<optgroup", ">", "</optgroup>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 11}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
