// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package checkbox

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/examples/shop/ui/checkbox",
		Name: "checkbox",
		Values: map[string]reflect.Value{
			"Checkbox":         reflect.ValueOf(Checkbox),
			"CheckboxFixtures": reflect.ValueOf(&CheckboxFixtures).Elem(),
		},
		Types: map[string]reflect.Type{
			"CheckboxProps": reflect.TypeFor[CheckboxProps](),
		},
		Methods: map[string]reflect.Value{
			"CheckboxProps.invalid": reflect.ValueOf(CheckboxProps.invalid),
		},
	}
}

var _ constant.Value
