// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package buttongroup

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/examples/shop/ui/button-group",
		Name: "buttongroup",
		Values: map[string]reflect.Value{
			"ButtonGroup":                  reflect.ValueOf(ButtonGroup),
			"ButtonGroupFixtures":          reflect.ValueOf(&ButtonGroupFixtures).Elem(),
			"ButtonGroupSeparator":         reflect.ValueOf(ButtonGroupSeparator),
			"ButtonGroupSeparatorFixtures": reflect.ValueOf(&ButtonGroupSeparatorFixtures).Elem(),
			"ButtonGroupSeparatorWrap":     reflect.ValueOf(ButtonGroupSeparatorWrap),
			"ButtonGroupText":              reflect.ValueOf(ButtonGroupText),
			"ButtonGroupTextFixtures":      reflect.ValueOf(&ButtonGroupTextFixtures).Elem(),
			"Horizontal":                   reflect.ValueOf(Horizontal),
			"Vertical":                     reflect.ValueOf(Vertical),
			"orientationClass":             reflect.ValueOf(&orientationClass).Elem(),
			"separatorClass":               reflect.ValueOf(&separatorClass).Elem(),
		},
		Types: map[string]reflect.Type{
			"ButtonGroupProps":          reflect.TypeFor[ButtonGroupProps](),
			"ButtonGroupSeparatorProps": reflect.TypeFor[ButtonGroupSeparatorProps](),
			"ButtonGroupTextProps":      reflect.TypeFor[ButtonGroupTextProps](),
			"Orientation":               reflect.TypeFor[Orientation](),
		},
		Methods: map[string]reflect.Value{
			"ButtonGroupProps.orientation":          reflect.ValueOf(ButtonGroupProps.orientation),
			"ButtonGroupSeparatorProps.orientation": reflect.ValueOf(ButtonGroupSeparatorProps.orientation),
		},
	}
}

var _ constant.Value
