// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package spinner

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/registry/spinner",
		Name: "spinner",
		Values: map[string]reflect.Value{
			"Spinner":         reflect.ValueOf(Spinner),
			"SpinnerFixtures": reflect.ValueOf(&SpinnerFixtures).Elem(),
		},
		Types: map[string]reflect.Type{
			"SpinnerProps": reflect.TypeFor[SpinnerProps](),
		},
		Methods: map[string]reflect.Value{
			"SpinnerProps.label": reflect.ValueOf(SpinnerProps.label),
		},
	}
}

var _ constant.Value
