// Code generated by gx. DO NOT EDIT.

package badge

import (
	gx "github.com/alternayte/gx"
)

type BadgeProps struct {
	// Variant sets the visual style: Default, Secondary, Destructive, Outline, Ghost or Link.
	Variant Variant
	// Href is the URL of the link. A non-empty value renders the badge as an a element, not a span.
	Href gx.URL
	// Class adds classes to the root element.
	Class string
	// Children is the badge label.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func Badge(p BadgeProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/badge", "Badge", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line Badge.gx:16:1
	if p.Href != "" {
//line Badge.gx:16:18
		_b.Add(_tBadge0.With(
//line Badge.gx:17:3
			gx.Open("a", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: p.class(), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "href", Value: string(p.Href), Kind: gx.AttrURL, Active: "page"}, gx.Attr{Key: "data-slot", Value: "badge", Kind: gx.AttrText}, gx.Attr{Key: "data-variant", Value: p.variant(), Kind: gx.AttrText}}, p.Attrs)),
//line Badge.gx:17:96
			p.Children,
		))
	} else {
//line Badge.gx:18:9
		_b.Add(_tBadge1.With(
//line Badge.gx:19:3
			gx.Open("span", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: p.class(), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "badge", Kind: gx.AttrText}, gx.Attr{Key: "data-variant", Value: p.variant(), Kind: gx.AttrText}}, p.Attrs)),
//line Badge.gx:19:85
			p.Children,
		))
	}
//line Badge.gx:20:2
	_b.Add(_tBadge2)
	return _b.Node()
}

var _tBadge0 = gx.NewTemplate(
	[]string{"\n  <a", ">", "</a>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 3, EndStatic: 2, End: 4}},
	[]gx.TemplateRoot{{El: -1, Slot: -1}, {El: 0, Slot: -1}, {El: -1, Slot: -1}},
)

var _tBadge1 = gx.NewTemplate(
	[]string{"\n  <span", ">", "</span>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 3, EndStatic: 2, End: 7}},
	[]gx.TemplateRoot{{El: -1, Slot: -1}, {El: 0, Slot: -1}, {El: -1, Slot: -1}},
)

var _tBadge2 = gx.NewTemplate(
	[]string{"\n"},
	[]int{},
	nil,
	[]gx.TemplateRoot{{El: -1, Slot: -1}},
).With()
