// Code generated by gx. DO NOT EDIT.

package breadcrumb

import (
	gx "github.com/alternayte/gx"
)

type BreadcrumbItemProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the content of the item: a BreadcrumbLink, a BreadcrumbPage or a
	// BreadcrumbEllipsis.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func BreadcrumbItem(p BreadcrumbItemProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/breadcrumb", "BreadcrumbItem", p); _ok {
			return _n
		}
	}
//line BreadcrumbItem.gx:13:1
	return _tBreadcrumbItem0.With(
//line BreadcrumbItem.gx:13:1
		gx.Open("li", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("inline-flex items-center gap-1.5", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "breadcrumb-item", Kind: gx.AttrText}}, p.Attrs)),
//line BreadcrumbItem.gx:13:105
		p.Children,
	)
}

var _tBreadcrumbItem0 = gx.NewTemplate(
	[]string{"<li", ">", "</li>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 5}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
