// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package gxdev_gallery

import (
	gx "github.com/alternayte/gx"
	docs "github.com/alternayte/gx/registry/docs"
)

// Fixtures returns every component fixture for the dev gallery
// (REQ-AI-03).
func Fixtures() []gx.Fixture {
	return []gx.Fixture{
		{Component: "Aside", Name: "Caution", Node: func() gx.Node { return docs.Aside(docs.AsideFixtures["Caution"]) }},
		{Component: "Aside", Name: "Danger", Node: func() gx.Node { return docs.Aside(docs.AsideFixtures["Danger"]) }},
		{Component: "Aside", Name: "Note", Node: func() gx.Node { return docs.Aside(docs.AsideFixtures["Note"]) }},
		{Component: "Aside", Name: "Tip", Node: func() gx.Node { return docs.Aside(docs.AsideFixtures["Tip"]) }},
		{Component: "Badge", Name: "Default", Node: func() gx.Node { return docs.Badge(docs.BadgeFixtures["Default"]) }},
		{Component: "Badge", Name: "Destructive", Node: func() gx.Node { return docs.Badge(docs.BadgeFixtures["Destructive"]) }},
		{Component: "Badge", Name: "Outline", Node: func() gx.Node { return docs.Badge(docs.BadgeFixtures["Outline"]) }},
		{Component: "Badge", Name: "Secondary", Node: func() gx.Node { return docs.Badge(docs.BadgeFixtures["Secondary"]) }},
		{Component: "Card", Name: "BodyOnly", Node: func() gx.Node { return docs.Card(docs.CardFixtures["BodyOnly"]) }},
		{Component: "Card", Name: "TitleAndBody", Node: func() gx.Node { return docs.Card(docs.CardFixtures["TitleAndBody"]) }},
		{Component: "Card", Name: "TitleOnly", Node: func() gx.Node { return docs.Card(docs.CardFixtures["TitleOnly"]) }},
		{Component: "CardGrid", Name: "Two", Node: func() gx.Node { return docs.CardGrid(docs.CardGridFixtures["Two"]) }},
		{Component: "Code", Name: "Go", Node: func() gx.Node { return docs.Code(docs.CodeFixtures["Go"]) }},
		{Component: "Code", Name: "Marked", Node: func() gx.Node { return docs.Code(docs.CodeFixtures["Marked"]) }},
		{Component: "FileTree", Name: "Tree", Node: func() gx.Node { return docs.FileTree(docs.FileTreeFixtures["Tree"]) }},
		{Component: "FileTreeItemRow", Name: "Dir", Node: func() gx.Node { return docs.FileTreeItemRow(docs.FileTreeItemRowFixtures["Dir"]) }},
		{Component: "FileTreeItemRow", Name: "File", Node: func() gx.Node { return docs.FileTreeItemRow(docs.FileTreeItemRowFixtures["File"]) }},
		{Component: "Hero", Name: "Full", Node: func() gx.Node { return docs.Hero(docs.HeroFixtures["Full"]) }},
		{Component: "Hero", Name: "Title", Node: func() gx.Node { return docs.Hero(docs.HeroFixtures["Title"]) }},
		{Component: "Icon", Name: "Decorative", Node: func() gx.Node { return docs.Icon(docs.IconFixtures["Decorative"]) }},
		{Component: "Icon", Name: "Labelled", Node: func() gx.Node { return docs.Icon(docs.IconFixtures["Labelled"]) }},
		{Component: "LinkButton", Name: "Ghost", Node: func() gx.Node { return docs.LinkButton(docs.LinkButtonFixtures["Ghost"]) }},
		{Component: "LinkButton", Name: "Outline", Node: func() gx.Node { return docs.LinkButton(docs.LinkButtonFixtures["Outline"]) }},
		{Component: "LinkButton", Name: "Primary", Node: func() gx.Node { return docs.LinkButton(docs.LinkButtonFixtures["Primary"]) }},
		{Component: "LinkButton", Name: "Secondary", Node: func() gx.Node { return docs.LinkButton(docs.LinkButtonFixtures["Secondary"]) }},
		{Component: "LinkCard", Name: "Full", Node: func() gx.Node { return docs.LinkCard(docs.LinkCardFixtures["Full"]) }},
		{Component: "LinkCard", Name: "Short", Node: func() gx.Node { return docs.LinkCard(docs.LinkCardFixtures["Short"]) }},
		{Component: "Steps", Name: "Three", Node: func() gx.Node { return docs.Steps(docs.StepsFixtures["Three"]) }},
		{Component: "TabItem", Name: "Text", Node: func() gx.Node { return docs.TabItem(docs.TabItemFixtures["Text"]) }},
		{Component: "Tabs", Name: "Synced", Node: func() gx.Node { return docs.Tabs(docs.TabsFixtures["Synced"]) }},
		{Component: "Tabs", Name: "Two", Node: func() gx.Node { return docs.Tabs(docs.TabsFixtures["Two"]) }},
	}
}
