// Code generated by gx. DO NOT EDIT.

package badge

import (
	gx "github.com/alternayte/gx"
)

type BadgeProps struct {
	Variant  Variant
	Href     gx.URL
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func Badge(p BadgeProps) gx.Node {
	var _b gx.Builder
//line Badge.gx:11:1
	if p.Href != "" {
//line Badge.gx:11:18
		_b.Add(gx.Text("\n  "))
//line Badge.gx:12:3
		_b.Add(gx.El("a", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: p.class(), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "href", Value: string(p.Href), Kind: gx.AttrURL, Active: "page"}, gx.Attr{Key: "data-slot", Value: "badge", Kind: gx.AttrText}, gx.Attr{Key: "data-variant", Value: p.variant(), Kind: gx.AttrText}}, p.Attrs), p.Children))
//line Badge.gx:12:112
		_b.Add(gx.Text("\n"))
	} else {
//line Badge.gx:13:9
		_b.Add(gx.Text("\n  "))
//line Badge.gx:14:3
		_b.Add(gx.El("span", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: p.class(), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "badge", Kind: gx.AttrText}, gx.Attr{Key: "data-variant", Value: p.variant(), Kind: gx.AttrText}}, p.Attrs), p.Children))
//line Badge.gx:14:104
		_b.Add(gx.Text("\n"))
	}
//line Badge.gx:15:2
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
