// Code generated by gx. DO NOT EDIT.

package menubar

import (
	gx "github.com/alternayte/gx"
)

type MenubarProps struct {
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func Menubar(p MenubarProps) gx.Node {
	var _b gx.Builder
//line Menubar.gx:9:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex h-9 items-center gap-1 rounded-md border border-border bg-background p-1 shadow-xs", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "role", Value: "menubar", Kind: gx.AttrText}, gx.Attr{Key: "data-gx-roving", Value: "nowrap", Kind: gx.AttrText}}, p.Attrs), p.Children))
//line Menubar.gx:9:190
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
