// Code generated by gx. DO NOT EDIT.

package menubar

import (
	gx "github.com/alternayte/gx"
)

type MenubarItemProps struct {
	// Variant sets the visual style: Default or Destructive.
	Variant Variant
	// Inset adds left padding, so the item lines up with the checkbox and radio items.
	Inset bool
	// Disabled turns the item off. The arrow keys pass it.
	Disabled bool
	// Class adds classes to the root element.
	Class string
	// Children is the content of the item.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func MenubarItem(p MenubarItemProps) gx.Node {
	var _b gx.Builder
//line MenubarItem.gx:18:1
	_b.Add(gx.El("button", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("relative flex w-full cursor-default items-center gap-2 rounded-sm px-2 py-1.5 text-left text-sm outline-hidden select-none hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4 [&_svg:not([class*='text-'])]:text-muted-foreground", variantClass[p.variant()], insetClass[p.Inset], p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "type", Value: "button", Kind: gx.AttrText}, gx.Attr{Key: "role", Value: "menuitem", Kind: gx.AttrText}, gx.Attr{Key: "tabindex", Value: "-1", Kind: gx.AttrText}, gx.Bool("disabled", p.Disabled), gx.Bool("data-gx-close", true)}, rovingItem(p.Disabled), p.Attrs), p.Children))
//line MenubarItem.gx:18:621
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
