// Code generated by gx. DO NOT EDIT.

package toast

import (
	gx "github.com/alternayte/gx"
)

type ToasterProps struct {
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func Toaster(p ToasterProps) gx.Node {
	var _b gx.Builder
//line Toaster.gx:9:1
	var _b1 gx.Builder
//line Toaster.gx:9:152
	_b1.Add(gx.Text("\n  "))
//line Toaster.gx:10:3
	if p.Children != nil {
//line Toaster.gx:10:25
		_b1.Add(gx.Text("\n    "))
//line Toaster.gx:11:5
		_b1.Add(p.Children)
//line Toaster.gx:11:17
		_b1.Add(gx.Text("\n  "))
	}
//line Toaster.gx:12:4
	_b1.Add(gx.Text("\n"))
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("fixed right-4 bottom-4 z-50 flex w-72 flex-col gap-2", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "id", Value: "gx-toaster", Kind: gx.AttrText}, gx.Attr{Key: "aria-live", Value: "polite", Kind: gx.AttrText}, gx.Attr{Key: "aria-atomic", Value: "true", Kind: gx.AttrText}}, p.Attrs), _b1.Node()))
//line Toaster.gx:13:7
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
