// Code generated by gx. DO NOT EDIT.

package textarea

import (
	gx "github.com/alternayte/gx"
)

type TextareaProps struct {
	// Name is the form field name.
	Name string
	// Value is the text of the textarea.
	Value string
	// Placeholder is the text that shows while the textarea is empty.
	Placeholder string
	// Rows is the rows attribute. A value of zero or less renders no attribute.
	Rows int
	// Class adds classes to the root element.
	Class string
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func Textarea(p TextareaProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/textarea", "Textarea", p); _ok {
			return _n
		}
	}
//line Textarea.gx:18:1
	return _tTextarea0.With(
//line Textarea.gx:18:1
		gx.Open("textarea", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx(Class, p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "name", Value: p.Name, Kind: gx.AttrText}, gx.Attr{Key: "placeholder", Value: p.Placeholder, Kind: gx.AttrText}, gx.Attr{Key: "data-slot", Value: "textarea", Kind: gx.AttrText}}, p.attrs())),
//line Textarea.gx:18:119
		gx.Text(p.Value),
	)
}

var _tTextarea0 = gx.NewTemplate(
	[]string{"<textarea", ">", "</textarea>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 11}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
