// Code generated by gx. DO NOT EDIT.

package hovercard

import (
	gx "github.com/alternayte/gx"
)

type HoverCardProps struct {
	Trigger  gx.Node
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func HoverCard(p HoverCardProps) gx.Node {
	var _b gx.Builder
//line HoverCard.gx:10:1
	_b.Add(gx.El("span", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("group relative inline-flex", p.Class), Kind: gx.AttrText}}, p.Attrs), gx.Frag(gx.Text("\n  "), p.Trigger, gx.Text("\n  "), gx.El("span", gx.Attrs{gx.Attr{Key: "class", Value: "pointer-events-none absolute top-full left-0 z-50 mt-2 hidden w-64 rounded-md border border-border bg-popover p-4 text-sm text-popover-foreground shadow-md group-hover:block group-focus-within:block", Kind: gx.AttrText}}, p.Children), gx.Text("\n"))))
//line HoverCard.gx:13:8
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
