// Code generated by gx. DO NOT EDIT.

package collapsible

import (
	gx "github.com/alternayte/gx"
)

type CollapsibleProps struct {
	Summary  gx.Node
	Open     bool
	Class    string
	Children gx.Node
	Attrs    gx.Attrs
}

func Collapsible(p CollapsibleProps) gx.Node {
	var _b gx.Builder
//line Collapsible.gx:11:1
	_b.Add(gx.El("details", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("group", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Bool("open", p.Open)}, p.Attrs), gx.Frag(gx.Text("\n  "), gx.El("summary", gx.Attrs{gx.Attr{Key: "class", Value: "flex cursor-pointer list-none items-center gap-2 [&::-webkit-details-marker]:hidden", Kind: gx.AttrText}}, p.Summary), gx.Text("\n  "), gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "pt-2", Kind: gx.AttrText}}, p.Children), gx.Text("\n"))))
//line Collapsible.gx:14:11
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
