// Code generated by gx. DO NOT EDIT.

//go:build gxdev

package login

import (
	"go/constant"
	"reflect"

	gx "github.com/alternayte/gx"
)

// GxDevSymbols lists the package-level names of this package for the dev
// interpreter (REQ-DEV-04).
func GxDevSymbols() gx.DevPackage {
	return gx.DevPackage{
		Path: "github.com/alternayte/gx/examples/shop/ui/login",
		Name: "login",
		Values: map[string]reflect.Value{
			"Login":         reflect.ValueOf(Login),
			"LoginFixtures": reflect.ValueOf(&LoginFixtures).Elem(),
		},
		Types: map[string]reflect.Type{
			"LoginProps": reflect.TypeFor[LoginProps](),
		},
	}
}

var _ constant.Value
