// Code generated by gx. DO NOT EDIT.

package route

import (
	gx "github.com/alternayte/gx"
	"net/http"
	"net/url"
	"strings"
)

// Pattern returns the method and pattern of Add.
func (Add) Pattern() string { return "POST /cart/add" }

// Bind fills Add from the request.
func (in *Add) Bind(r *http.Request) error {
	signals, err := gx.Signals(r)
	if err != nil {
		return err
	}
	if err := gx.BindSignal(signals, gx.Scope(r), "qty", &in.Qty); err != nil {
		return err
	}
	return nil
}

// URL returns the path of Add.
func (in Add) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("cart")
	b.WriteString("/")
	b.WriteString("add")
	return gx.BasePath() + b.String()
}

// Pattern returns the method and pattern of Error.
func (Error) Pattern() string { return "POST /cart/error" }

// Bind fills Error from the request.
func (in *Error) Bind(r *http.Request) error {
	return nil
}

// URL returns the path of Error.
func (in Error) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("cart")
	b.WriteString("/")
	b.WriteString("error")
	return gx.BasePath() + b.String()
}

// Pattern returns the method and pattern of Lazy.
func (Lazy) Pattern() string { return "GET /lazy" }

// Bind fills Lazy from the request.
func (in *Lazy) Bind(r *http.Request) error {
	return nil
}

// URL returns the path of Lazy.
func (in Lazy) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("lazy")
	return gx.BasePath() + b.String()
}

// Pattern returns the method and pattern of Noop.
func (Noop) Pattern() string { return "POST /cart/noop" }

// Bind fills Noop from the request.
func (in *Noop) Bind(r *http.Request) error {
	return nil
}

// URL returns the path of Noop.
func (in Noop) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("cart")
	b.WriteString("/")
	b.WriteString("noop")
	return gx.BasePath() + b.String()
}

// Pattern returns the method and pattern of Redirect.
func (Redirect) Pattern() string { return "POST /cart/redirect" }

// Bind fills Redirect from the request.
func (in *Redirect) Bind(r *http.Request) error {
	return nil
}

// URL returns the path of Redirect.
func (in Redirect) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("cart")
	b.WriteString("/")
	b.WriteString("redirect")
	return gx.BasePath() + b.String()
}

// Pattern returns the method and pattern of Set.
func (Set) Pattern() string { return "POST /cart/set" }

// Bind fills Set from the request.
func (in *Set) Bind(r *http.Request) error {
	return nil
}

// URL returns the path of Set.
func (in Set) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("cart")
	b.WriteString("/")
	b.WriteString("set")
	return gx.BasePath() + b.String()
}

// Pattern returns the method and pattern of Toast.
func (Toast) Pattern() string { return "POST /cart/toast" }

// Bind fills Toast from the request.
func (in *Toast) Bind(r *http.Request) error {
	return nil
}

// URL returns the path of Toast.
func (in Toast) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("cart")
	b.WriteString("/")
	b.WriteString("toast")
	return gx.BasePath() + b.String()
}

// Pattern returns the method and pattern of ToastDemo.
func (ToastDemo) Pattern() string { return "POST /cart/toast-demo" }

// Bind fills ToastDemo from the request.
func (in *ToastDemo) Bind(r *http.Request) error {
	if v := r.URL.Query().Get("show"); v != "" {
		in.Show = string(v)
	}
	return nil
}

// URL returns the path of ToastDemo.
func (in ToastDemo) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("cart")
	b.WriteString("/")
	b.WriteString("toast-demo")
	q := url.Values{}
	if in.Show != "" {
		q.Set("show", in.Show)
	}
	if s := q.Encode(); s != "" {
		b.WriteString("?")
		b.WriteString(s)
	}
	return gx.BasePath() + b.String()
}

// Pattern returns the method and pattern of Transition.
func (Transition) Pattern() string { return "POST /cart/transition" }

// Bind fills Transition from the request.
func (in *Transition) Bind(r *http.Request) error {
	return nil
}

// URL returns the path of Transition.
func (in Transition) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("cart")
	b.WriteString("/")
	b.WriteString("transition")
	return gx.BasePath() + b.String()
}

// Pattern returns the method and pattern of Undo.
func (Undo) Pattern() string { return "POST /cart/undo" }

// Bind fills Undo from the request.
func (in *Undo) Bind(r *http.Request) error {
	return nil
}

// URL returns the path of Undo.
func (in Undo) URL() string {
	var b strings.Builder
	b.WriteString("/")
	b.WriteString("cart")
	b.WriteString("/")
	b.WriteString("undo")
	return gx.BasePath() + b.String()
}
