// Code generated by gx. DO NOT EDIT.

package tabs

import (
	gx "github.com/alternayte/gx"
)

type TabsContentProps struct {
	// Label is the label of the trigger that shows this panel.
	Label string
	// Class adds classes to the root element.
	Class string
	// Children is the content of the panel.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func TabsContent(p TabsContentProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/tabs", "TabsContent", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line TabsContent.gx:14:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex-1 outline-none", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "role", Value: "tabpanel", Kind: gx.AttrText}, gx.Attr{Key: "tabindex", Value: "0", Kind: gx.AttrText}, gx.Attr{Key: "data-gx-tab-panel", Value: p.Label, Kind: gx.AttrText}}, p.Attrs), p.Children))
//line TabsContent.gx:14:140
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
