// Code generated by gx. DO NOT EDIT.

package collapsible

import (
	gx "github.com/alternayte/gx"
)

type CollapsibleProps struct {
	// Summary is the content of the summary, the part that opens and closes the panel.
	Summary gx.Node
	// Open renders the collapsible open. The default is closed.
	Open bool
	// Class adds classes to the root element.
	Class string
	// Children is the content of the panel.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func Collapsible(p CollapsibleProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/collapsible", "Collapsible", p); _ok {
			return _n
		}
	}
//line Collapsible.gx:16:1
	return _tCollapsible0.With(
//line Collapsible.gx:16:1
		gx.Open("details", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("group/collapsible [interpolate-size:allow-keywords] [&::details-content]:h-0 [&::details-content]:overflow-hidden [&::details-content]:transition-[height,content-visibility] [&::details-content]:transition-discrete [&::details-content]:duration-200 [&::details-content]:ease-out open:[&::details-content]:h-auto motion-reduce:[&::details-content]:transition-none", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Bool("open", p.Open)}, p.Attrs)),
//line Collapsible.gx:17:213
		p.Summary,
//line Collapsible.gx:18:3
		p.Children,
	)
}

var _tCollapsible0 = gx.NewTemplate(
	[]string{"<details", ">\n  <summary class=\"inline-flex cursor-pointer list-none items-center gap-2 rounded-md outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] [&amp;::-webkit-details-marker]:hidden\">", "</summary>\n  ", "\n</details>\n"},
	[]int{0, 2, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 3, End: 11}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
