// Code generated by gx. DO NOT EDIT.

package popover

import (
	gx "github.com/alternayte/gx"
)

type PopoverDescriptionProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the text of the description.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func PopoverDescription(p PopoverDescriptionProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/popover", "PopoverDescription", p); _ok {
			return _n
		}
	}
//line PopoverDescription.gx:12:1
	return _tPopoverDescription0.With(
//line PopoverDescription.gx:12:1
		gx.Open("p", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("text-muted-foreground", p.Class), Kind: gx.AttrText}}, p.Attrs)),
//line PopoverDescription.gx:12:65
		p.Children,
	)
}

var _tPopoverDescription0 = gx.NewTemplate(
	[]string{"<p", ">", "</p>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 4}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
