// Code generated by gx. DO NOT EDIT.

package popover

import (
	gx "github.com/alternayte/gx"
)

type PopoverHeaderProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the content of the header, usually a title and a description.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func PopoverHeader(p PopoverHeaderProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/examples/shop/ui/popover", "PopoverHeader", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line PopoverHeader.gx:12:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("flex flex-col gap-1 text-sm", p.Class), Kind: gx.AttrText}}, p.Attrs), p.Children))
//line PopoverHeader.gx:12:91
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
