// Code generated by gx. DO NOT EDIT.

package drawer

import (
	gx "github.com/alternayte/gx"
)

type DrawerProps struct {
	// Id is the id of the dialog element.
	// The trigger points at it, so it must be unique on the page.
	Id string
	// Side sets the edge the drawer slides from: Bottom, Top, Right or Left.
	Side Side
	// Title is the heading of the drawer. An empty value renders no heading.
	Title string
	// Description is the text below the title. An empty value renders no description.
	Description string
	// Trigger is the control that opens the drawer.
	Trigger gx.Node
	// Footer is the content of the drawer footer. A nil value renders no footer.
	Footer gx.Node
	// Open renders the drawer open. The default is closed.
	Open bool
	// Class adds classes to the dialog element.
	Class string
	// Children is the content of the drawer body.
	Children gx.Node
	// Attrs adds HTML attributes to the dialog element.
	Attrs gx.Attrs
}

func Drawer(p DrawerProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/drawer", "Drawer", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line Drawer.gx:27:1
	var _b1 gx.Builder
//line Drawer.gx:27:24
	_b1.Add(gx.Text("\n  "))
//line Drawer.gx:28:3
	if p.Trigger != nil {
//line Drawer.gx:28:24
		_b1.Add(gx.Text("\n    "))
//line Drawer.gx:29:5
		_b1.Add(gx.El("span", gx.Attrs{gx.Attr{Key: "class", Value: "contents", Kind: gx.AttrText}, gx.Attr{Key: "data-gx-open", Value: "#" + p.Id, Kind: gx.AttrText}}, p.Trigger))
//line Drawer.gx:29:72
		_b1.Add(gx.Text("\n  "))
	}
//line Drawer.gx:30:4
	_b1.Add(gx.Text("\n  "))
//line Drawer.gx:31:3
	var _b2 gx.Builder
//line Drawer.gx:31:635
	_b2.Add(gx.Text("\n    "))
//line Drawer.gx:32:5
	_b2.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "mx-auto mt-4 hidden h-2 w-[100px] shrink-0 rounded-full bg-muted group-data-[side=bottom]/drawer-content:block", Kind: gx.AttrText}}))
//line Drawer.gx:32:135
	_b2.Add(gx.Text("\n    "))
//line Drawer.gx:33:5
	if p.Title != "" || p.Description != "" {
//line Drawer.gx:33:46
		_b2.Add(gx.Text("\n      "))
//line Drawer.gx:34:7
		var _b3 gx.Builder
//line Drawer.gx:34:171
		_b3.Add(gx.Text("\n        "))
//line Drawer.gx:35:9
		if p.Title != "" {
//line Drawer.gx:35:27
			_b3.Add(gx.Text("\n          "))
//line Drawer.gx:36:11
			_b3.Add(gx.El("h2", gx.Attrs{gx.Attr{Key: "class", Value: "font-semibold text-foreground", Kind: gx.AttrText}}, gx.Text(p.Title)))
//line Drawer.gx:36:67
			_b3.Add(gx.Text("\n        "))
		}
//line Drawer.gx:37:10
		_b3.Add(gx.Text("\n        "))
//line Drawer.gx:38:9
		if p.Description != "" {
//line Drawer.gx:38:33
			_b3.Add(gx.Text("\n          "))
//line Drawer.gx:39:11
			_b3.Add(gx.El("p", gx.Attrs{gx.Attr{Key: "class", Value: "text-sm text-muted-foreground", Kind: gx.AttrText}}, gx.Text(p.Description)))
//line Drawer.gx:39:71
			_b3.Add(gx.Text("\n        "))
		}
//line Drawer.gx:40:10
		_b3.Add(gx.Text("\n      "))
		_b2.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "flex flex-col gap-0.5 p-4 group-data-[side=bottom]/drawer-content:text-center group-data-[side=top]/drawer-content:text-center md:gap-1.5 md:text-left", Kind: gx.AttrText}}, _b3.Node()))
//line Drawer.gx:41:13
		_b2.Add(gx.Text("\n    "))
	}
//line Drawer.gx:42:6
	_b2.Add(gx.Text("\n    "))
//line Drawer.gx:43:5
	if p.Children != nil {
//line Drawer.gx:43:27
		_b2.Add(gx.Text("\n      "))
//line Drawer.gx:44:7
		_b2.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "overflow-y-auto p-4 pt-0 text-sm", Kind: gx.AttrText}}, p.Children))
//line Drawer.gx:44:71
		_b2.Add(gx.Text("\n    "))
	}
//line Drawer.gx:45:6
	_b2.Add(gx.Text("\n    "))
//line Drawer.gx:46:5
	if p.Footer != nil {
//line Drawer.gx:46:25
		_b2.Add(gx.Text("\n      "))
//line Drawer.gx:47:7
		_b2.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "mt-auto flex flex-col gap-2 p-4", Kind: gx.AttrText}}, p.Footer))
//line Drawer.gx:47:68
		_b2.Add(gx.Text("\n    "))
	}
//line Drawer.gx:48:6
	_b2.Add(gx.Text("\n  "))
	_b1.Add(gx.El("dialog", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("group/drawer-content fixed m-0 max-h-none max-w-none flex-col border-border bg-background text-foreground outline-none open:flex transition-[translate,overlay,display] transition-discrete duration-300 ease-in-out open:duration-500 motion-reduce:transition-none backdrop:bg-black/50 backdrop:opacity-0 backdrop:transition-[opacity,overlay,display] backdrop:transition-discrete backdrop:duration-200 open:backdrop:opacity-100 starting:open:backdrop:opacity-0 motion-reduce:backdrop:transition-none", p.sideClass(), p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "id", Value: p.Id, Kind: gx.AttrText}, gx.Bool("open", p.Open), gx.Bool("data-gx-dismiss", true), gx.Bool("data-gx-trap", true), gx.Attr{Key: "data-side", Value: p.side(), Kind: gx.AttrText}}, p.Attrs), _b2.Node()))
//line Drawer.gx:49:12
	_b1.Add(gx.Text("\n"))
	_b.Add(gx.El("span", gx.Attrs{gx.Attr{Key: "class", Value: "contents", Kind: gx.AttrText}}, _b1.Node()))
//line Drawer.gx:50:8
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
