// Code generated by gx. DO NOT EDIT.

package datatablepage

import (
	gx "github.com/alternayte/gx"
	"github.com/alternayte/gx/examples/shop/ui/card"
)

type DataTablePageProps struct {
	Title       string
	Description string
	Filter      gx.Node
	Table       gx.Node
	Pagination  gx.Node
}

func DataTablePage(p DataTablePageProps) gx.Node {
	var _b gx.Builder
//line DataTablePage.gx:16:1
	var _b1 gx.Builder
//line DataTablePage.gx:16:59
	_b1.Add(gx.Text("\n  "))
//line DataTablePage.gx:17:3
	var _b2 gx.Builder
//line DataTablePage.gx:17:63
	_b2.Add(gx.Text("\n    "))
//line DataTablePage.gx:18:5
	var _b3 gx.Builder
//line DataTablePage.gx:18:38
	_b3.Add(gx.Text("\n      "))
//line DataTablePage.gx:19:7
	_b3.Add(gx.El("h1", gx.Attrs{gx.Attr{Key: "class", Value: "text-xl font-semibold", Kind: gx.AttrText}}, gx.Text(p.Title)))
//line DataTablePage.gx:19:55
	_b3.Add(gx.Text("\n      "))
//line DataTablePage.gx:20:7
	if p.Description != "" {
//line DataTablePage.gx:20:31
		_b3.Add(gx.Text("\n        "))
//line DataTablePage.gx:21:9
		_b3.Add(gx.El("p", gx.Attrs{gx.Attr{Key: "class", Value: "text-sm text-muted-foreground", Kind: gx.AttrText}}, gx.Text(p.Description)))
//line DataTablePage.gx:21:69
		_b3.Add(gx.Text("\n      "))
	}
//line DataTablePage.gx:22:8
	_b3.Add(gx.Text("\n    "))
	_b2.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "flex flex-col gap-1", Kind: gx.AttrText}}, _b3.Node()))
//line DataTablePage.gx:23:11
	_b2.Add(gx.Text("\n    "))
//line DataTablePage.gx:24:5
	if p.Filter != nil {
//line DataTablePage.gx:24:25
		_b2.Add(gx.Text("\n      "))
//line DataTablePage.gx:25:7
		_b2.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "w-56", Kind: gx.AttrText}}, gx.Frag(gx.Text("\n        "), p.Filter, gx.Text("\n      "))))
//line DataTablePage.gx:27:13
		_b2.Add(gx.Text("\n    "))
	}
//line DataTablePage.gx:28:6
	_b2.Add(gx.Text("\n  "))
	_b1.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "flex flex-wrap items-end justify-between gap-4", Kind: gx.AttrText}}, _b2.Node()))
//line DataTablePage.gx:29:9
	_b1.Add(gx.Text("\n  "))
//line DataTablePage.gx:30:3
	_b1.Add(card.Card(card.CardProps{Title: "", Description: "", Footer: nil, Class: "", Children: p.Table, Attrs: nil}))
//line DataTablePage.gx:32:15
	_b1.Add(gx.Text("\n  "))
//line DataTablePage.gx:33:3
	if p.Pagination != nil {
//line DataTablePage.gx:33:27
		_b1.Add(gx.Text("\n    "))
//line DataTablePage.gx:34:5
		_b1.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "flex justify-center", Kind: gx.AttrText}}, p.Pagination))
//line DataTablePage.gx:34:58
		_b1.Add(gx.Text("\n  "))
	}
//line DataTablePage.gx:35:4
	_b1.Add(gx.Text("\n"))
	_b.Add(gx.El("div", gx.Attrs{gx.Attr{Key: "class", Value: "mx-auto flex w-full max-w-5xl flex-col gap-6", Kind: gx.AttrText}}, _b1.Node()))
//line DataTablePage.gx:36:7
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
