// Code generated by gx. DO NOT EDIT.

package field

import (
	gx "github.com/alternayte/gx"
)

type FieldGroupProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the content of the group: the fields, the field sets and the separators.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func FieldGroup(p FieldGroupProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/field", "FieldGroup", p); _ok {
			return _n
		}
	}
	var _b gx.Builder
//line FieldGroup.gx:12:1
	_b.Add(gx.El("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("group/field-group @container/field-group flex w-full flex-col gap-7 data-[slot=checkbox-group]:gap-3 [&>[data-slot=field-group]]:gap-4", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "field-group", Kind: gx.AttrText}}, p.Attrs), p.Children))
//line FieldGroup.gx:12:222
	_b.Add(gx.Text("\n"))
	return _b.Node()
}
