// Code generated by gx. DO NOT EDIT.

package field

import (
	gx "github.com/alternayte/gx"
)

type FieldGroupProps struct {
	// Class adds classes to the root element.
	Class string
	// Children is the content of the group: the fields, the field sets and the separators.
	Children gx.Node
	// Attrs adds HTML attributes to the root element.
	Attrs gx.Attrs
}

func FieldGroup(p FieldGroupProps) gx.Node {
	if gx.Dev {
		if _n, _ok := gx.DevRender("github.com/alternayte/gx/registry/field", "FieldGroup", p); _ok {
			return _n
		}
	}
//line FieldGroup.gx:12:1
	return _tFieldGroup0.With(
//line FieldGroup.gx:12:1
		gx.Open("div", gx.JoinAttrs(gx.Attrs{gx.Attr{Key: "class", Value: gx.Cx("group/field-group @container/field-group flex w-full flex-col gap-7 data-[slot=checkbox-group]:gap-3 [&>[data-slot=field-group]]:gap-4", p.Class), Kind: gx.AttrText}}, gx.Attrs{gx.Attr{Key: "data-slot", Value: "field-group", Kind: gx.AttrText}}, p.Attrs)),
//line FieldGroup.gx:12:204
		p.Children,
	)
}

var _tFieldGroup0 = gx.NewTemplate(
	[]string{"<div", ">", "</div>\n"},
	[]int{0, 1},
	[]gx.TemplateEl{{Slot: 0, Start: 0, EndStatic: 2, End: 6}},
	[]gx.TemplateRoot{{El: 0, Slot: -1}, {El: -1, Slot: -1}},
)
